### ISSUE TITLE
Summary Count and Specimens Count with No Facets Selected off by One on Staging

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/azul#156] opened 2018-08-02 10:29 UTC
Organ shows 184 specimens, Summary shows 183.
This is on stage with no facets selected.
Staging points to prod.

![Screen Shot 2018-08-02 at 8.23.42 PM.png](https://images.zenhubusercontent.com/57323611bf93871ccd9ad094/d88ddf43-f30a-491c-97a6-37cf3fa40316)

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/AZUL-117)
┆Project Name: azul
┆Issue Number: AZUL-117

**Comment by achave11** [comment] 2018-08-30 23:26
Closing ticket. It is a duplicate of  #186

**Comment by achave11** [comment] 2018-08-30 23:27
Closing ticket. It is a duplicate of #186

**Closed** 2018-09-01 00:00 UTC
Labels: bug
