### ISSUE TITLE
2 primary bundles and 13 analysis bundles not indexed in 03/01 scale test run

### ISSUE THREAD

**Issue by parthshahva** [DataBiosphere/azul#773] opened 2019-03-08 06:08 UTC
Submission ID: 5c78bb0206bd55000b84d84e
Project UUID: 4c21b606-4a30-46a6-80a1-5cb1074badf9
Environment: Integration
Test identifier: scale/ss2_2000/2019-03-01T04:54:21Z
dcp-diag output

PHASE 6: Check Azul for primary bundles:
Counting bundles in webservice...done.
In Azul, 2 primary bundles are NOT indexed
61e027e9-8a32-4ae1-9626-dc786d332a2f.2019-03-01T164452.929390Z
791906ba-aecf-4ff1-8f7e-69f977e1d993.2019-03-01T171043.987329Z

PHASE 7: Check Azul for secondary bundles:
In Azul there are 1927 primary bundles with 1 results bundles (expected: 1940)
13 of the 35 primary bundles below should have an indexed analysis bundle
primary: a0b6ca5d-cb54-4974-bc77-4b8e467ae23f.2019-03-01T164247.207545Z secondary: []
		primary: c153bd5c-eeaf-4c22-8a78-c9213abe75af.2019-03-01T164858.909710Z secondary: []
		primary: 8126615b-8d84-4a6b-9cd8-e2c04e32922a.2019-03-01T165818.361516Z secondary: []
		primary: eea6350e-4a46-4975-8051-62972196e052.2019-03-01T171702.013493Z secondary: []
		primary: a09c420a-ec1f-455f-806b-9e614ce2e988.2019-03-01T172725.186058Z secondary: []
		primary: 84d45517-2823-42c0-bf5f-0d35f86af7a5.2019-03-01T173846.454978Z secondary: []
		primary: 560b43a0-9377-4e50-b63b-0a465c22de90.2019-03-01T180028.977546Z secondary: []
		primary: f1caa499-d933-4a5a-89f3-18321ebf41ef.2019-03-01T180132.539928Z secondary: []
		primary: 954f42c0-d348-422c-a29c-303469d95f52.2019-03-01T180747.476944Z secondary: []
		primary: b9495dcd-3800-4239-b0e4-7eb9961753fe.2019-03-01T180849.822166Z secondary: []
		primary: a27c0dd5-4323-4659-a927-2aca48b8b9ae.2019-03-01T181256.541387Z secondary: []
		primary: e3a542ae-2f3a-46c6-b168-bac755556722.2019-03-01T181414.592705Z secondary: []
		primary: 857efbb4-3e32-45fe-8589-6c4cf18c4f34.2019-03-01T182113.906914Z secondary: []
		primary: ecc27089-283d-4447-a2e6-ed9ac2fd4b4c.2019-03-01T182929.506943Z secondary: []
		primary: f8b78b65-1e69-468d-8f7e-742bff1e5ea0.2019-03-01T183236.177669Z secondary: []
		primary: 2748c846-6055-4b85-bad2-74f8bfa2c03e.2019-03-01T183745.445133Z secondary: []
		primary: 6456a6c0-67fd-4995-b47d-a4a639f1d50b.2019-03-01T184211.734211Z secondary: []
		primary: 0d87bcc9-495c-42d6-a622-f9eb7e051b00.2019-03-01T184619.016127Z secondary: []
		primary: c71dadb5-27e2-421c-9074-7084f9766496.2019-03-01T185210.587868Z secondary: []
		primary: d5e2a044-4524-4033-976c-6793f3ce9e97.2019-03-01T185229.500326Z secondary: []
		primary: 9bfe3ef5-abdc-421d-903f-60c4e242f2e9.2019-03-01T185412.620251Z secondary: []
		primary: e77e84f0-42a7-4a72-97eb-a84650843fb3.2019-03-01T185518.272099Z secondary: []
		primary: b4abda41-a2d6-4000-a360-1bf980433672.2019-03-01T185518.422533Z secondary: []
		primary: d04dc529-5875-4c21-b5ac-3203ed23cd77.2019-03-01T185736.978594Z secondary: []
		primary: e6c0e9c9-00ec-45a6-b663-78641df1887f.2019-03-01T190532.560212Z secondary: []
		primary: 6b705b8c-f139-4d34-9fd1-b058eda88acb.2019-03-01T191852.723378Z secondary: []
		primary: 77ae1282-731e-4d6f-883e-7d117cf03df1.2019-03-01T191859.440640Z secondary: []
		primary: 45e67acf-ca82-4296-9227-1dac2d169017.2019-03-01T192012.140377Z secondary: []
		primary: e2adc139-e20c-47f6-8841-da244ac645ab.2019-03-01T192104.872397Z secondary: []
		primary: e8883968-3ccf-48ad-a91c-f78c914d2948.2019-03-01T192513.769193Z secondary: []
		primary: cd55ed00-0eaf-47ae-a065-205166f08627.2019-03-01T192644.271517Z secondary: []
		primary: 1b427713-5f81-4b8b-885d-3d5e239dfee4.2019-03-01T193446.126567Z secondary: []
		primary: ae9ecfd6-ad3a-443c-a9f5-8fc45df23088.2019-03-01T194753.623319Z secondary: []
		primary: 971c6c10-9689-4154-b8b7-bfd468ceef21.2019-03-01T194753.587083Z secondary: []
		primary: 88e9f41f-3115-4479-880e-4122e239a6fa.2019-03-01T195709.429201Z secondary: []

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-478)
┆Project Name: azul
┆Issue Number: AZUL-478

**Comment by hannes-ucsc** [comment] 2019-03-08 07:13
Thank you for filing this, @parthshahva. In the recent 10 days, our `staging` and `integration` deployments were compromised by https://github.com/DataBiosphere/azul/issues/771. The bundle version from this test fall into that date range. I'd like to sit on this until next time the scale tests are  run.

**Comment by hannes-ucsc** [comment] 2019-03-08 07:13
#771 is fixed as of today.

**Comment by theathorn** [comment] 2019-03-11 18:22
Check with Parth to see if this is fixed now.

**Comment by hannes-ucsc** [comment] 2019-03-27 07:07
We weren't able to run the scale test during this sprint. I'm just gonna close this one. We are 90% certain that the duplicate notifications were the cause. Please reopen of this occurs again

**Closed by hannes-ucsc** 2019-03-27 07:07 UTC
Labels: bug, code
