### ISSUE TITLE
Figure out linking of data files to metadata files in TDR

### ISSUE THREAD

**Issue by melainalegaspi** [DataBiosphere/azul#1922] opened 2020-06-24 18:37 UTC

**Comment by hannes-ucsc** [comment] 2020-06-25 06:10
https://github.com/DataBiosphere/hca-metadata-api/blob/afa44a9f2548aff235f4a838359298a832ed1a8d/src/humancellatlas/data/metadata/api.py#L621

is where a metadata entity describing a data file is linked to the manifest entry for the data file it describes.

The TDR table row for that metadata entity has a `descriptor` column and a `contents` column, both containing JSON. The `contents` column contains the `file_core.file_name` property referenced in the above line of code. The `descriptor` also has a `file_name` property but it is set to the the path to the data file relative to the staging bucket. When faking out the manifest entries for data files, the TDR plugin needs to essentially set `manifest_entry.file_name` to `tdr_row.contents.file_core.file_name` instead of `tdr_row.descriptor.file_name` for the above line in metadata API to work as intended.

**Comment by hannes-ucsc** [comment] 2020-06-25 06:11
Assigned to @danielsotirhos and @noah-aviel-dove for review of the above.

**Comment by danielsotirhos** [comment] 2020-06-25 18:24
Approved.
It might be worth noting that the DSS Adapter writes the file_descriptor's `file_name` value using the syntax "{bundle-uuid}/{file_name}" (eg. `"file_name": "a0688b93-7f46-486d-9c11-7ea55587b5e3/TissueDissociationProtocol.pdf",`) so the desired value for the fake manifest entry could be parsed out of this.

**Comment by noah-aviel-dove** [comment] 2020-06-25 20:52
Makes sense to me.

**Closed** 2020-06-29 18:25 UTC
Labels: code, orange, task
