### ISSUE TITLE
IT `_assert_catalog_empty` in `sandbox` fails

### ISSUE THREAD

**Issue by achave11** [DataBiosphere/azul#3264] opened 2021-07-22 21:29 UTC
The following [IT failure](https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/24933#L1642) was observed in `sandbox` deployment:
```
FAIL: test_indexing (integration_test.IndexingIntegrationTest) [catalog_empty] (catalog='it2ebi', entity_type='files')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builds/ucsc/azul/test/integration_test.py", line 175, in subTest
    yield
  File "/builds/ucsc/azul/test/integration_test.py", line 692, in _assert_catalog_empty
    self.assertEqual([], [hit['entryId'] for hit in hits])
AssertionError: Lists differ: [] != ['fc467e99-f670-5e81-ab39-631a62114103']
Second list contains 1 additional elements.
First extra element 0:
'fc467e99-f670-5e81-ab39-631a62114103'
- []
+ ['fc467e99-f670-5e81-ab39-631a62114103']
----------------------------------------------------------------------
Ran 11 tests in 1222.500s
FAILED (failures=1, skipped=3)
make: *** [Makefile:168: integration_test] Error 1
Cleaning up file based variables
00:01
ERROR: Job failed: exit code 1
```

It appears that some content was still present after deletion notifications were processed.

**Comment by amarjandu** [comment] 2021-07-22 22:01
Dupe of https://github.com/DataBiosphere/azul/issues/3233 ?

**Comment by melainalegaspi** [comment] 2021-07-22 22:12
@hannes-ucsc to decide if a duplicate or not.

**Comment by hannes-ucsc** [comment] 2021-07-22 23:46
Duplicates #2330. That might not be obvious from the symptoms in the description of that ticket, but we updated the assertion code and [later comments] link to IT failures that resemble the symptom listed in this issue.

**Closed by hannes-ucsc** 2021-07-22 23:46 UTC
Labels: bug, code, duplicate, orange
