### ISSUE TITLE
Needless layer update when deploying same commit twice

### ISSUE THREAD

**Issue by achave11-ucsc** [DataBiosphere/azul#5454] opened 2023-08-04 17:56 UTC
For example the initial attempt: 

https://gitlab.azul.data.humancellatlas.org/ucsc/azul/-/jobs/43572

The consecutive attempts had a change to `source_code_hash` …

https://gitlab.azul.data.humancellatlas.org/ucsc/azul/-/jobs/43581

https://gitlab.azul.data.humancellatlas.org/ucsc/azul/-/jobs/43584

https://gitlab.azul.data.humancellatlas.org/ucsc/azul/-/jobs/43615

… but the last  one did not:

https://gitlab.azul.data.humancellatlas.org/ucsc/azul/-/jobs/43622

- [ ] Security design review completed; the Resolution of this issue does **not** …
  - [ ] … affect authentication; for example:
    - OAuth 2.0 with the application (API or Swagger UI)
    - Authentication of developers with Google Cloud APIs
    - Authentication of developers with AWS APIs
    - Authentication with a GitLab instance in the system
    - Password and 2FA authentication with GitHub
    - API access token authentication with GitHub
    - Authentication with 
  - [ ] … affect the permissions of internal users like access to
    - Cloud resources on AWS and GCP
    - GitLab repositories, projects and groups, administration
    - an EC2 instance via SSH
    - GitHub issues, pull requests, commits, commit statuses, wikis, repositories, organizations
  - [ ] … affect the permissions of external users like access to
    - TDR snapshots
  - [ ] … affect permissions of service or bot accounts
    - Cloud resources on AWS and GCP
  - [ ] … affect audit logging in the system, like
    - adding, removing or changing a log message that represents an auditable event
    - changing the routing of log messages through the system
  - [ ] … affect monitoring of the system
  - [ ] … introduce a new software dependency like
    - Python packages on PYPI
    - Command-line utilities
    - Docker images
    - Terraform providers
  - [ ] … add an interface that exposes sensitive or confidential data at the security boundary
  - [ ] … affect the encryption of data at rest
  - [ ] … require persistence of sensitive or confidential data that might require encryption at rest
  - [ ] … require unencrypted transmission of data within the security boundary
  - [ ] … affect the network security layer; for example by 
    - modifying, adding or removing firewall rules
    - modifying, adding or removing security groups
    - changing or adding a port a service, proxy or load balancer listens on
- [ ] Documentation on any unchecked boxes is provided in comments below

**Comment by achave11-ucsc** [comment] 2023-08-04 19:14
Spike to diagnose.

**Comment by nadove-ucsc** [comment] 2023-08-09 06:46
I reproduced the source hash changing locally, but I think the explanation is a red herring and more work is needed to explain what we observed on GitLab.

When running `make -C lambdas/` in a clean working tree (e.g. after running `make clean`), the `compile` make target is run before the `package` target (both defined in `lambdas.mk`. In addition to `deployment.zip`, package also creates the files `lambdas/{service,indexer}/vendor/azul_changes.py`. If `package` in run again without cleaning up the artifacts from the previous packaging, the `compile` target will create `lambdas/{service,indexer}/vendor/__pycache__/azul_changes.cpython-39.pyc`, which will be included in `deployment.zip`. Since this file did not exist during the previous invocation of `package`, the zip file is now different.

I don't think this explains the source hash changing on GitLab because each jobs runs `make clean` before deploying the lambdas.

**Comment by nadove-ucsc** [comment] 2023-08-10 03:40
The source code hash appears to depend on which GitLab runner (Azul #1 or Azul #2) handled the given deploy job. The hashes consistently alternated between two sets of values depending on which runner handled the job. If the same runner was used twice in a row, the hash was consistent and Terraform did not try to update the resources.

<google-sheets-html-origin>

Job index | Job began | Runner | Terraform deployed changes? | Indexer source hash | Service source hash
-- | -- | -- | -- | -- | --
1 | Aug 3, 2023 4:11pm PDT | Azul #1 41xfExGK, system ID: r_ehAxEPhjHRY2 | Yes | BomngEEhsg4dms3N3kD8maYzGAioKsaI8lN89YqS6tM= | v1A9p93lTWHgrAQiIBwny0+Ybxua0ecP70abxqypTwQ=
2 | Aug 3, 2023 4:28pm PDT | Azul #2 -Yx3sf9Z, system ID: r_ehAxEPhjHRY2 | Yes | YzAwiD7QnfVHNXIRANwg8kvUfmkW7PQxS1Eak8Sw0Yw= | JyB2OgkJLxjDywjQ21iKBUI6oBAQo9DAbHDcqmQFY3s=
3 | Aug 3, 2023 5:37pm PDT | Azul #1 41xfExGK, system ID: r_ehAxEPhjHRY2 | Yes | BomngEEhsg4dms3N3kD8maYzGAioKsaI8lN89YqS6tM= | v1A9p93lTWHgrAQiIBwny0+Ybxua0ecP70abxqypTwQ=
4 | Aug 4, 2023 7:40am PDT | Azul #2 -Yx3sf9Z, system ID: r_ehAxEPhjHRY2 | Yes | YzAwiD7QnfVHNXIRANwg8kvUfmkW7PQxS1Eak8Sw0Yw= | JyB2OgkJLxjDywjQ21iKBUI6oBAQo9DAbHDcqmQFY3s=
5 | Aug 4, 2023 10:36am PDT | Azul #2 -Yx3sf9Z, system ID: r_ehAxEPhjHRY2 | No | N/A | N/A
6 | Aug 4, 2023 10:57am PDT | Azul #1 41xfExGK, system ID: r_ehAxEPhjHRY2 | Yes | BomngEEhsg4dms3N3kD8maYzGAioKsaI8lN89YqS6tM= | v1A9p93lTWHgrAQiIBwny0+Ybxua0ecP70abxqypTwQ=
7 | Aug 4, 2023 1:46pm PDT | Azul #1 41xfExGK, system ID: r_ehAxEPhjHRY2 | No | N/A | N/A
8 | Aug 7, 2023 10:44am PDT | Azul #1 41xfExGK, system ID: r_ehAxEPhjHRY2 | No | N/A | N/A

**Comment by nadove-ucsc** [comment] 2023-08-10 03:56
Issue title is therefore slightly inaccurate, as the source code hash did not change on _every_ retry of the deploy job.

**Comment by nadove-ucsc** [comment] 2023-08-10 04:51
Looking through the version history of the prod `tfstate` in S3 reveals a consistent difference in `source_code_size` that correlates with the differences in `source_code_hash` and the runner ID. The service and indexer lambdas are 8 bytes larger when packaged on Azul #2 compared to Azul #1.

```
$ for f in $(ls); do echo $f; grep source_code_size $f | sort | uniq; done
08-03-16_15.json
            "source_code_size": 1236629,
            "source_code_size": 1249769,
            "source_code_size": 28288928,
08-03-16_32.json
            "source_code_size": 1236637,
            "source_code_size": 1249777,
            "source_code_size": 28288928,
08-03-17_40.json
            "source_code_size": 1236629,
            "source_code_size": 1249769,
            "source_code_size": 28288928,
08-04-07_44.json
            "source_code_size": 1236637,
            "source_code_size": 1249777,
            "source_code_size": 28288928,
08-04-10_38.json
            "source_code_size": 1236637,
            "source_code_size": 1249777,
            "source_code_size": 28288928,
08-04-11_00.json
            "source_code_size": 1236629,
            "source_code_size": 1249769,
            "source_code_size": 28288928,
08-04-13_47.json
            "source_code_size": 1236629,
            "source_code_size": 1249769,
            "source_code_size": 28288928,
08-07-10_46.json
            "source_code_size": 1236629,
            "source_code_size": 1249769,
            "source_code_size": 28288928,
```

**Comment by nadove-ucsc** [comment] 2023-08-10 06:45
To resolve the difference between these two versions of the deployment, we'd need to compare the two zip files generated by each runner. The most recent package (created by runner #1) can be downloaded from the AWS console, but unfortunately I don't think there's any way to recover the older packages, since they aren't saved on GitLab and we don't publish versions of our lambdas.

So, I think we need to retry the deploy job _again_, potentially multiple times, until the job is picked up by runner #2 instead of runner #1. That should reproduce the hash inconsistency. Then we can download runner #2's package and compare it directly to runner #1's (which I already have downloaded), which should illuminate the exact inconsistency between the two.

**Comment by nadove-ucsc** [comment] 2023-08-10 19:33
Decided at PL to try and replicate on a GitLab instance for one of the lower deployments to avoid touching `prod` while Hannes is away.

**Comment by nadove-ucsc** [comment] 2023-08-11 02:42
Reproduced the same pattern of alternating source hashes on GitLab `dev` by retrying [the most recent `deploy` job](https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/73992). Downloaded and compared `deployment.zip` files created by each of the two runners via the AWS Lambda console.

Four files differ between the two packages:

```
humancellatlas/data/metadata/__pycache__/lookup.cpython-39.pyc
humancellatlas/data/metadata/__pycache__/datetime.cpython-39.pyc
humancellatlas/data/metadata/__pycache__/api.cpython-39.pyc
humancellatlas/data/metadata/__pycache__/age_range.cpython-39.pyc
```

The difference occurs at the 9th byte in each file, at the start of the [marshal dump](https://docs.fileformat.com/executable/pyc/#structure-of-pyc-file-format). Trying to read the data using the `marshal` module fails with the error:

```
ValueError: bad marshal data (unknown type code)
```

Still struggling to understand this.

**Comment by nadove-ucsc** [comment] 2023-08-11 09:28
I still don't understand what's going on with the contents of these `.pyc` files, but I think the root cause is this line:

https://github.com/DataBiosphere/azul/blob/afdd6a7600d2668b26b590c42dd00e7c2bca0d3a/lambdas/lambdas.mk#L33

`vendor/azul` is explicitly included in the arguments to `compileall`, but `vendor/humancellatlas` is not. I don't understand why we pass both `vendor/` and `vendor/azul`, but it seems for consistency we need to pass `vendor/humancellatlas` as well in order for the `pyc` files in that directory to be consistent like the ones in `vendor/azul` are. Need to test this hypothesis on GitLab.

**Comment by nadove-ucsc** [comment] 2023-08-12 03:07
[Test](https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/74063) successful. Adding the `vendor/humancellatlas` directory as an explicit argument to `compileall` appears to resolve the inconsistency.

<google-sheets-html-origin>

1 | Aug 11, 2023 6:34pm PDT | Azul #2 xHQi2x_S, system ID: r_HXUshJtjLOSP | Yes | Jikmt6HTm3wGnRjVfag1hsP8dGiztVOfb94x0rzArVg= | 94lKWswU+0GH8Pey9hhN1WJBQt5zkE3P06pCUm5aG+g=
-- | -- | -- | -- | -- | --
2 | Aug 11, 2023 7:19pm PDT | Azul #1 nJ9KdGyH, system ID: r_HXUshJtjLOSP | No | N/A | N/A
3 | Aug 11, 2023 7:31pm PDT | Azul #2 xHQi2x_S, system ID: r_HXUshJtjLOSP | No | N/A | N/A
4 | Aug 11, 2023 7:37pm PDT | Azul #2 xHQi2x_S, system ID: r_HXUshJtjLOSP | No | N/A | N/A
5 | Aug 11, 2023 7:45pm PDT | Azul #2 xHQi2x_S, system ID: r_HXUshJtjLOSP | No | N/A | N/A
6 | Aug 11, 2023 7:51pm PDT | Azul #1 nJ9KdGyH, system ID: r_HXUshJtjLOSP | No | N/A | N/A
7 | Aug 11, 2023 7:57pm PDT | Azul #2 xHQi2x_S, system ID: r_HXUshJtjLOSP | No | N/A | N/A
8 | Aug 11, 2023 8:01pm PDT | Azul #1 nJ9KdGyH, system ID: r_HXUshJtjLOSP | No | N/A | N/A

**Comment by dsotirho-ucsc** [comment] 2023-09-05 19:00
@hannes-ucsc to review solution.

**Comment by hannes-ucsc** [comment] 2023-09-08 16:02
I'll handle this as a WIP review of the connected draft PR.

**Comment by hannes-ucsc** [comment] 2023-09-12 16:40
For demo, attempt to reproduce.

**Closed as completed** 2023-10-03 20:43 UTC
Labels: demoed, infra, spike:5, spike:8, demo
