### ISSUE TITLE
Reconsider TDR plugin's dependency on `dcp-type`

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#2100] opened 2020-07-31 18:29 UTC
In the DSS, the `content-type` property of a bundle manifest entry for a metadata file includes the `; dcp-type=…` extension.

```
{
    "name": "specimen_from_organism_0.json",
    "uuid": "d6a518a8-0c5d-4cb0-aed5-68f3455c2bda",
    "version": "2019-09-20T134352.654000Z",
    "content-type": "application/json; dcp-type=\"metadata/biomaterial\"",
    "size": 1300,
    "indexed": true,
    "crc32c": "ef2adac7",
    "sha1": "2270093c55e4e5d1cc6b68ef60cb6c8abd6127ae",
    "sha256": "f4688fdb5c6b9b18c3993599c1d6a853070889eb702a06fae790409699c292c1",
    "s3_etag": "3f17191e3721a119a85fc0ea784c0a81"
}
```

AFAIK, no one uses that extension.

I noticed that the TDR plugin references `dcp-type` in various places, even to drive whether the emulated manifest entry's `indexed` property is True or False. This confuses me. Every row in a TDR table for DCP/2 is by definition a metadata entity and needs to have `indexed` set to True.

`dcp-type` is dead weight. We shouldn't depend on it and we should minimize the number of references to it in our code base.

**Comment by melainalegaspi** [comment] 2020-11-06 00:18
@noah-aviel-dove is this a duplicate of #2363?

**Comment by noah-aviel-dove** [comment] 2020-11-06 01:08
> @noah-aviel-dove is this a duplicate of #2363?

No, #2363 only affects the `links` entities, this is much more general.

**Comment by noah-aviel-dove** [comment] 2020-12-18 02:50
> Every row in a TDR table for DCP/2 is by definition a metadata entity and needs to have indexed set to True.

Rows in tables corresponding to file-type entities, e.g. `sequence_file`, expand into two entities per row: 

1. A metadata entity identified by `<row>.sequence_file_id` where `indexed` is set to True.
2. A data entity identified by `<row>.descriptor.file_id` where `indexed` is set to False.

**Comment by noah-aviel-dove** [comment] 2020-12-22 08:01
The TDR plugin was designed to emulate the manifest output of the DSS plugin as precisely as possible, including the presence of the `dcp-type` extension. The value of `dcp-type` emitted by the plugin is synthesized from the `schema_type` attribute of the metadata content; there is no _input_ called `dcp-type`.

It's simple to set the `indexed` attribute based on a different condition, but other references to `dcp-type` cannot be removed without removing `dcp-type` from the TDR Plugin's output, which would introduce an avoidable discrepancy with the DSS plugin and require further additions to the recanning script. This is perfectly doable but I want to confirm whether it's covered by the intent behind the ticket.

**Closed** 2021-02-10 18:37 UTC
Labels: code, debt, no demo, orange
