### ISSUE TITLE
IT failure due to TDR response timeout

### ISSUE THREAD

**Issue by amarjandu** [DataBiosphere/azul#4083] opened 2022-04-13 06:13 UTC
The `dev` TDR instance is taking longer than 5 seconds to return a response for the /snapshots/ endpoint, this is causing pipeline failures for our `sandbox` and `dev` deployments.

Dev:
https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/43408
https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/43421 (retry)

Sandbox:
https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/43417

(#4066):
https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/43394

```
======================================================================
ERROR: test_indexing (integration_test.IndexingIntegrationTest) [managed_access_repository_sources]
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/build/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.8/http/client.py", line 1348, in getresponse
    response.begin()
  File "/usr/local/lib/python3.8/http/client.py", line 316, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.8/http/client.py", line 277, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/usr/local/lib/python3.8/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/local/lib/python3.8/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/build/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/build/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 447, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/build/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 336, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='jade.datarepo-dev.broadinstitute.org', port=443): Read timed out. (read timeout=5.0)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/builds/ucsc/azul/test/integration_test.py", line 354, in subTest
    yield
  File "/builds/ucsc/azul/test/integration_test.py", line 960, in _test_managed_access
    public_source_ids = self._test_managed_access_repository_sources(catalog,
  File "/builds/ucsc/azul/test/integration_test.py", line 996, in _test_managed_access_repository_sources
    with self._unregistered_service_account_credentials:
  File "/builds/ucsc/azul/test/integration_test.py", line 548, in _unregistered_service_account_credentials
    return self._authorization_context(self._unregistered_tdr_client)
  File "/builds/ucsc/azul/src/azul/caching.py", line 189, in __get__
    value = obj.__dict__[self.fget.__name__] = self.fget(obj)
  File "/builds/ucsc/azul/test/integration_test.py", line 215, in _unregistered_tdr_client
    self.assertRaises(RequirementError, tdr.snapshot_names_by_id)
  File "/usr/local/lib/python3.8/unittest/case.py", line 816, in assertRaises
    return context.handle('assertRaises', args, kwargs)
  File "/usr/local/lib/python3.8/unittest/case.py", line 202, in handle
    callable_obj(*args, **kwargs)
  File "/builds/ucsc/azul/src/azul/terra.py", line 515, in snapshot_names_by_id
    response = self._request('GET', endpoint, fields={
  File "/builds/ucsc/azul/src/azul/terra.py", line 298, in _request
    response = self._http_client.request(method,
  File "/build/.venv/lib/python3.8/site-packages/urllib3/request.py", line 74, in request
    return self.request_encode_url(
  File "/build/.venv/lib/python3.8/site-packages/urllib3/request.py", line 96, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
  File "/build/.venv/lib/python3.8/site-packages/google/auth/transport/urllib3.py", line 388, in urlopen
    response = self.http.urlopen(
  File "/build/.venv/lib/python3.8/site-packages/urllib3/poolmanager.py", line 375, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/build/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 783, in urlopen
    return self.urlopen(
  File "/build/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 783, in urlopen
    return self.urlopen(
  File "/build/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 783, in urlopen
    return self.urlopen(
  File "/build/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/build/.venv/lib/python3.8/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='jade.datarepo-dev.broadinstitute.org', port=443): Max retries exceeded with url: /api/repository/v1/snapshots?offset=0&limit=200&sort=created_date&direction=asc (Caused by ReadTimeoutError("HTTPSConnectionPool(host='jade.datarepo-dev.broadinstitute.org', port=443): Read timed out. (read timeout=5.0)"))
======================================================================
ERROR: test_indexing (integration_test.IndexingIntegrationTest) [managed_access_manifest]
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builds/ucsc/azul/test/integration_test.py", line 354, in subTest
    yield
  File "/builds/ucsc/azul/test/integration_test.py", line 973, in _test_managed_access
    first(public_source_ids & indexed_source_ids))
UnboundLocalError: local variable 'public_source_ids' referenced before assignment
----------------------------------------------------------------------
```

**Comment by amarjandu** [comment] 2022-04-13 16:37
When attempting to replicate the request using the token from `azul-ucsc-0-unreg-dev@platform-hca-dev.iam.gserviceaccount.com` we observe the request taking ~30 seconds to complete and a 500 error being returned.
 
```
(.venv) CBSEspecter:azul amar$ time curl -v -X 'GET'   'https://jade.datarepo-dev.broadinstitute.org/api/repository/v1/snapshots?offset=0&limit=200'   -H 'accept: application/json'   -H 'Authorization: Bearer REDACTED
Note: Unnecessary use of -X or --request, GET is already inferred.
*   Trying 130.211.17.99...
* TCP_NODELAY set
* Connected to jade.datarepo-dev.broadinstitute.org (130.211.17.99) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-CHACHA20-POLY1305
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=jade.datarepo-dev.broadinstitute.org
*  start date: Mar 27 09:47:34 2022 GMT
*  expire date: Jun 25 09:47:33 2022 GMT
*  subjectAltName: host "jade.datarepo-dev.broadinstitute.org" matched cert's "jade.datarepo-dev.broadinstitute.org"
*  issuer: C=US; O=Let's Encrypt; CN=R3
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x7ff74e008200)
> GET /api/repository/v1/snapshots?offset=0&limit=200 HTTP/2
> Host: jade.datarepo-dev.broadinstitute.org
> User-Agent: curl/7.64.1
> accept: application/json
> Authorization: Bearer REDACTED
>
* Connection state changed (MAX_CONCURRENT_STREAMS == 100)!
< HTTP/2 500
< date: Wed, 13 Apr 2022 16:11:48 GMT
< server: Apache
< x-frame-options: SAMEORIGIN
< access-control-allow-headers: DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization,Accept,Referer,X-App-Id,Origin
< access-control-allow-methods: GET,POST,DELETE,PUT,PATCH,OPTIONS,HEAD
< x-content-type-options: nosniff
< strict-transport-security: max-age=31536000;includeSubDomains
< cache-control: no-cache,no-store,must-revalidate
< x-request-id: 6WOLGmdn
< content-type: application/json
< content-length: 31
< vary: Origin
< via: 1.1 google
< alt-svc: clear
<
* Connection #0 to host jade.datarepo-dev.broadinstitute.org left intact
{"message":"","errorDetail":[]}* Closing connection 0

real	0m30.604s
user	0m0.025s
sys	0m0.022s
```

**Comment by hannes-ucsc** [comment] 2022-04-13 16:46
Two observations: 

1) The TDR client should be using the 20s timeout in this situation since it is not in a Lambda context.

2) The UnboundLocalError at the bottom of the description hints that there is a problem with nesting sub tests.

Spike to diagnose and file separate tickets, if necessary.

**Comment by amarjandu** [comment] 2022-04-13 17:41
`UnboundLocalError` is being tracked https://github.com/DataBiosphere/azul/issues/4053

Looking at the 20 second timeout used during IT.

**Comment by noah-aviel-dove** [comment] 2022-04-13 19:12
```diff
Index: test/integration_test.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/test/integration_test.py b/test/integration_test.py
--- a/test/integration_test.py	(revision fe1d2842e42040c36c69a0e88e5a1ab1702cf8dd)
+++ b/test/integration_test.py	(date 1649876494501)
@@ -212,6 +212,7 @@
                          f'The "unregistered" service account ({email!r}) has '
                          f'been registered')
         # The unregistered service account should not have access to any sources
+        # FIXME should be more specific, looking for the 401 case
         self.assertRaises(RequirementError, tdr.snapshot_names_by_id)
         return tdr
 ```

**Comment by hannes-ucsc** [comment] 2022-04-13 19:52
@noah-aviel-dove to confirm that the unbound local in this backtrace (see description) is fixed by the solution for #4053.

**Comment by hannes-ucsc** [comment] 2022-04-13 20:17
Terra folks confirmed that they are working on a fix so that Terra returns a 401 when the `enumerateSnapshots` endpoint is hit with the token of an unregistered user. Until the fix lands, file a partial PR that disables the call to `tdr.snapshot_names_by_id` in `_unregistered_tdr_client`.

**Comment by hannes-ucsc** [comment] 2022-04-13 20:18
Also add a FIXME to re-enable the call once this issue is fixed.

**Comment by noah-aviel-dove** [comment] 2022-04-13 20:54
> @noah-aviel-dove to confirm that the unbound local in this backtrace (see description) is fixed by the solution for https://github.com/DataBiosphere/azul/issues/4053.

Haven't tested it but I'm entirely confident that they're the same error and it will be fixed by https://github.com/DataBiosphere/azul/pull/4078

**Comment by theathorn** [comment] 2022-04-18 19:09
Waiting for TDR to return 401 immediately (see above Slack thread).

**Comment by theathorn** [comment] 2022-04-18 23:34
From Nicolas Malfroy-Camine in Slack: "This should be live on dev now and should be released to prod tomorrow".

**Comment by theathorn** [comment] 2022-04-19 18:40
@hannes-ucsc : "@amarjandu to verify fix is in TDR dev"

**Comment by achave11** [comment] 2022-04-19 19:06
I think this might still be failing… https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/43915
This type of error has been observed during the promotion pipeline while running `sandbox` PRs this week.

**Comment by amarjandu** [comment] 2022-04-19 20:58
@achave11 Thanks for bringing this up, I'll try to reproduce it although it might be transient as the following IT passes. We might want to re-prioritize https://github.com/DataBiosphere/azul/issues/3643 in light of the issues we saw last week.

**Comment by amarjandu** [comment] 2022-04-19 23:02
```python
from azul.terra import (
    TDRClient,
    ServiceAccountCredentialsProvider,
)
from azul import config
import requests
tdr = TDRClient(
    credentials_provider=ServiceAccountCredentialsProvider(
        service_account=config.ServiceAccount.unregistered
    )
)
url = 'https://jade.datarepo-dev.broadinstitute.org/api/repository/v1/snapshots?offset=0&limit=200'
a = requests.get(url, headers={'Authorization': 'Bearer ' + tdr.credentials.token,
                               'Content-Type': 'application/json'})
a.status_code, a.elapsed
(401, datetime.timedelta(microseconds=202003))
```

Confirmed that `tdr-dev` is currently returning 401 responses and not taking ~30 seconds to respond as was observed in the reproduction https://github.com/DataBiosphere/azul/issues/4083#issuecomment-1098262166

**Comment by theathorn** [comment] 2022-04-20 18:51
@hannes-ucsc : Given @amarjandu 's verification and the promise by Broad for this to land in prod today, we'll be promoting the solution for the blocked ticket next week.

**Closed by theathorn** 2022-04-20 18:51 UTC
Labels: bug, orange, no demo, spike:1, blocked

**Comment by theathorn** [comment] 2022-04-21 18:00
When I asked Nicolas if the fix was on TDR prod: "Not yet. It should be this afternoon."

**Comment by theathorn** [comment] 2022-04-21 21:19
Nicolas: "We just released so this should be on prod now".
