### ISSUE TITLE
Summary and Pagination Total Don't Match on Dev

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/azul#186] opened 2018-08-13 04:21 UTC
Take a look at the response from:

https://service.dev.explore.data.humancellatlas.org/repository/specimens?size=15&filters=%7B%7D

and

https://service.dev.explore.data.humancellatlas.org/repository/files/summary?filters=%7B%7D

The /repository/specimens in the pagination are returns:
```
pagination": {
    "count": 15,
    "total": 414,
    "size": 15,
    "search_after": "f7db639a-9cd7-4a5c-8260-c2dc0dedd592",
    "search_after_uid": "doc#f7db639a-9cd7-4a5c-8260-c2dc0dedd592",
    "search_before": null,
    "search_before_uid": null,
    "pages": 28,
    "sort": "entity_id",
    "order": "desc"
  },
```

But the summary returns:

```
{
  "fileCount": 20885,
  "specimenCount": 139,
  "projectCount": 111,
  "totalFileSize": 15350291353461,
  "organCount": 5,
  "donorCount": 24,
  "labCount": 5,
  "totalCellCount": 0,
  "fileTypeSummaries": [
    {
      "fileType": "fastq.gz",
      "count": 20885,
      "totalSize": 15350291353461
    }
  ],
  "organSummaries": [
    {
      "organType": "brain",
      "countOfDocsWithOrganType": 20107,
      "totalCellCountByOrgan": 0
    },
    {
      "organType": "hematopoietic system",
      "countOfDocsWithOrganType": 762,
      "totalCellCountByOrgan": 0
    },
    {
      "organType": "spleen",
      "countOfDocsWithOrganType": 12,
      "totalCellCountByOrgan": 0
    },
    {
      "organType": "lymph node",
      "countOfDocsWithOrganType": 2,
      "totalCellCountByOrgan": 0
    },
    {
      "organType": "tumor",
      "countOfDocsWithOrganType": 2,
      "totalCellCountByOrgan": 0
    }
  ]
}
```

I am expecting the summary.specimenCount to equal the pagination.total but the summaryCount is 414 and the pagination.total is 139.

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/AZUL-137)
┆Project Name: azul
┆Issue Number: AZUL-137

**Comment by theathorn** [comment] 2018-08-13 17:02
Related to #156.

**Comment by achave11** [comment] 2018-08-31 20:17
Duplicate of #156, closing.

**Closed by achave11** 2018-08-31 20:17 UTC
Labels: bug
