### ISSUE TITLE
Add managed-access snapshots to `pilot` catalog in `prod`

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#5785] opened 2023-12-13 00:05 UTC
There are supposed to be snapshots for three MA project but we don't know yet which ones.

**Comment by achave11-ucsc** [comment] 2023-12-13 19:41
Assignee to stay in touch with HCA and put ticket back to triage as soon as the snapshots are available.

**Comment by bvizzier-ucsc** [comment] 2023-12-14 21:06
I have selected these because they are smaller (overall size) and appear to have a relatively complete set of files and file types.

https://explore.data.humancellatlas.org/projects/520afa10-f9d2-4e93-ab7a-26c4c863ce18
https://explore.data.humancellatlas.org/projects/8559a8ed-5d8c-4fb6-bde8-ab639cebf03c

**Comment by bvizzier-ucsc** [comment] 2024-04-15 18:59
Requesting review of this ticket with respect to #6156

**Comment by achave11-ucsc** [comment] 2024-04-16 18:50
Duplicate of #6156. See PR #6157 ([e61cf78](https://github.com/DataBiosphere/azul/commit/e61cf78376257ed6127efceab601de7aab66c5f2))

**Closed as not planned by achave11-ucsc** 2024-04-16 18:50 UTC
Labels: duplicate, infra
