### ISSUE TITLE
GitHub API rate limit exceeded in `test_canned_staging_area`

### ISSUE THREAD

**Issue by nadove-ucsc** [DataBiosphere/azul#4757] opened 2022-11-22 08:28 UTC
https://github.com/DataBiosphere/azul/actions/runs/3521443550/jobs/5903293677  

~May be a dupe of~ Likely duplicated by https://github.com/DataBiosphere/azul/issues/4438

- [x] Security design review completed; the Resolution of this issue does **not** …
  - [x] … affect authentication; for example:
    - OAuth 2.0 with the application (API or Swagger UI)
    - Authentication of developers with Google Cloud APIs
    - Authentication of developers with AWS APIs
    - Authentication with a GitLab instance in the system
    - Password and 2FA authentication with GitHub
    - API access token authentication with GitHub
    - Authentication with 
  - [x] … affect the permissions of internal users like access to
    - Cloud resources on AWS and GCP
    - GitLab repositories, projects and groups, administration
    - an EC2 instance via SSH
    - GitHub issues, pull requests, commits, commit statuses, wikis, repositories, organizations
  - [x] … affect the permissions of external users like access to
    - TDR snapshots
  - [x] … affect permissions of service or bot accounts
    - Cloud resources on AWS and GCP
  - [x] … affect audit logging in the system, like
    - adding, removing or changing a log message that represents an auditable event
    - changing the routing of log messages through the system
  - [x] … affect monitoring of the system
  - [x] … introduce a new software dependency like
    - Python packages on PYPI
    - Command-line utilities
    - Docker images
    - Terraform providers
  - [x] … add an interface that exposes sensitive or confidential data at the security boundary
  - [x] … affect the encryption of data at rest
  - [x] … require persistence of sensitive or confidential data that might require encryption at rest
  - [x] … require unencrypted transmission of data within the security boundary
  - [x] … affect the network security layer; for example by 
    - modifying, adding or removing firewall rules
    - modifying, adding or removing security groups
    - changing or adding a port a service, proxy or load balancer listens on
- [x] Documentation on any unchecked boxes is provided in comments below

**Comment by dsotirho-ucsc** [comment] 2022-11-22 19:55
@hannes-ucsc: "Not exactly a duplicate of #4438 but the solution is likely the same for both: find a more efficient way of extracting the metadata files from the staging area. I'm thinking we should clone the repository in a temporary directory and extract the files from the clone instead of the GitHub server."

**Comment by achave11-ucsc** [comment] 2023-03-01 21:15
EDIT: This is in the wrong issue, see below.

It seems like the reference link in the description expired and the stack trace isn't accessible. But two recent builds have fail this test with different stack traces.

https://github.com/DataBiosphere/azul/actions/runs/4307226400/jobs/7512033686

```
======================================================================
ERROR: test_canned_staging_area (hca_metadata_api.test.TestAccessorApi)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/azul/azul/.venv/lib/python3.9/site-packages/jsonschema/validators.py", line 909, in resolve_from_url
    document = self.store[url]
  File "/home/runner/work/azul/azul/.venv/lib/python3.9/site-packages/jsonschema/_utils.py", line 28, in __getitem__
    return self.store[self.normalize(uri)]
KeyError: 'https://schema.staging.data.humancellatlas.org/system/1.1.0/provenance'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/azul/azul/.venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/home/runner/work/azul/azul/.venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/home/runner/work/azul/azul/.venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/home/runner/work/azul/azul/.venv/lib/python3.9/site-packages/urllib3/connection.py", line 414, in connect
    self.sock = ssl_wrap_socket(
  File "/home/runner/work/azul/azul/.venv/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/home/runner/work/azul/azul/.venv/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/opt/hostedtoolcache/Python/3.9.12/x64/lib/python3.9/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/opt/hostedtoolcache/Python/3.9.12/x64/lib/python3.9/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/opt/hostedtoolcache/Python/3.9.12/x64/lib/python3.9/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/azul/azul/.venv/lib/python3.9/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/home/runner/work/azul/azul/.venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/home/runner/work/azul/azul/.venv/lib/python3.9/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/runner/work/azul/azul/.venv/lib/python3.9/site-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/home/runner/work/azul/azul/.venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/home/runner/work/azul/azul/.venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/home/runner/work/azul/azul/.venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/home/runner/work/azul/azul/.venv/lib/python3.9/site-packages/urllib3/connection.py", line 414, in connect
    self.sock = ssl_wrap_socket(
  File "/home/runner/work/azul/azul/.venv/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/home/runner/work/azul/azul/.venv/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/opt/hostedtoolcache/Python/3.9.12/x64/lib/python3.9/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/opt/hostedtoolcache/Python/3.9.12/x64/lib/python3.9/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/opt/hostedtoolcache/Python/3.9.12/x64/lib/python3.9/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/azul/azul/.venv/lib/python3.9/site-packages/jsonschema/validators.py", line 912, in resolve_from_url
    document = self.resolve_remote(url)
  File "/home/runner/work/azul/azul/.venv/lib/python3.9/site-packages/jsonschema/validators.py", line 1015, in resolve_remote
    result = requests.get(uri).json()
  File "/home/runner/work/azul/azul/.venv/lib/python3.9/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/home/runner/work/azul/azul/.venv/lib/python3.9/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/runner/work/azul/azul/.venv/lib/python3.9/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/runner/work/azul/azul/.venv/lib/python3.9/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/home/runner/work/azul/azul/.venv/lib/python3.9/site-packages/requests/adapters.py", line 547, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/azul/azul/test/hca_metadata_api/test.py", line 489, in test_canned_staging_area
    staging_area = factory.load_staging_area()
  File "/home/runner/work/azul/azul/src/humancellatlas/data/metadata/helpers/staging_area.py", line 279, in load_staging_area
    files = self._get_files(path=self.path + ('metadata', folder))
  File "/home/runner/work/azul/azul/src/humancellatlas/data/metadata/helpers/staging_area.py", line 316, in _get_files
    file = JsonFile.from_json(file_name, file_json)
  File "/home/runner/work/azul/azul/src/humancellatlas/data/metadata/helpers/staging_area.py", line 85, in from_json
    return MetadataFile(uuid=entity_id,
  File "<attrs generated init humancellatlas.data.metadata.helpers.staging_area.MetadataFile>", line 8, in __init__
    self.__attrs_post_init__()
  File "/home/runner/work/azul/azul/src/humancellatlas/data/metadata/helpers/staging_area.py", line 60, in __attrs_post_init__
    self._validator.validate_json(self.content, self.name)
  File "/home/runner/work/azul/azul/src/humancellatlas/data/metadata/helpers/schema_validation.py", line 34, in validate_json
    validate(file_json, schema, format_checker=FormatChecker())
  File "/home/runner/work/azul/azul/.venv/lib/python3.9/site-packages/jsonschema/validators.py", line 1119, in validate
    error = exceptions.best_match(validator.iter_errors(instance))
  File "/home/runner/work/azul/azul/.venv/lib/python3.9/site-packages/jsonschema/exceptions.py", line 384, in best_match
    best = next(errors, None)
  File "/home/runner/work/azul/azul/.venv/lib/python3.9/site-packages/jsonschema/validators.py", line 288, in iter_errors
    for error in errors:
  File "/home/runner/work/azul/azul/.venv/lib/python3.9/site-packages/jsonschema/_validators.py", line 332, in properties
    yield from validator.descend(
  File "/home/runner/work/azul/azul/.venv/lib/python3.9/site-packages/jsonschema/validators.py", line 305, in descend
    for error in self.evolve(schema=schema).iter_errors(instance):
  File "/home/runner/work/azul/azul/.venv/lib/python3.9/site-packages/jsonschema/validators.py", line 288, in iter_errors
    for error in errors:
  File "/home/runner/work/azul/azul/.venv/lib/python3.9/site-packages/jsonschema/_validators.py", line 294, in ref
    scope, resolved = validator.resolver.resolve(ref)
  File "/home/runner/work/azul/azul/.venv/lib/python3.9/site-packages/jsonschema/validators.py", line 898, in resolve
    return url, self._remote_cache(url)
  File "/home/runner/work/azul/azul/.venv/lib/python3.9/site-packages/jsonschema/validators.py", line 914, in resolve_from_url
    raise exceptions.RefResolutionError(exc)
jsonschema.exceptions.RefResolutionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

----------------------------------------------------------------------
Ran 394 tests in 935.556s

FAILED (errors=1, skipped=4)
make: *** [Makefile:224: test] Error 1
Error: Process completed with exit code 2.
```

and https://github.com/DataBiosphere/azul/actions/runs/4307236496/jobs/7512056296

```
======================================================================
ERROR: test_canned_staging_area (hca_metadata_api.test.TestAccessorApi)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/azul/azul/.venv/lib/python3.9/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/opt/hostedtoolcache/Python/3.9.12/x64/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/opt/hostedtoolcache/Python/3.9.12/x64/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/hostedtoolcache/Python/3.9.12/x64/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/azul/azul/.venv/lib/python3.9/site-packages/jsonschema/validators.py", line 912, in resolve_from_url
    document = self.resolve_remote(url)
  File "/home/runner/work/azul/azul/.venv/lib/python3.9/site-packages/jsonschema/validators.py", line 1015, in resolve_remote
    result = requests.get(uri).json()
  File "/home/runner/work/azul/azul/.venv/lib/python3.9/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/azul/azul/test/hca_metadata_api/test.py", line 489, in test_canned_staging_area
    staging_area = factory.load_staging_area()
  File "/home/runner/work/azul/azul/src/humancellatlas/data/metadata/helpers/staging_area.py", line 279, in load_staging_area
    files = self._get_files(path=self.path + ('metadata', folder))
  File "/home/runner/work/azul/azul/src/humancellatlas/data/metadata/helpers/staging_area.py", line 316, in _get_files
    file = JsonFile.from_json(file_name, file_json)
  File "/home/runner/work/azul/azul/src/humancellatlas/data/metadata/helpers/staging_area.py", line 85, in from_json
    return MetadataFile(uuid=entity_id,
  File "<attrs generated init humancellatlas.data.metadata.helpers.staging_area.MetadataFile>", line 8, in __init__
    self.__attrs_post_init__()
  File "/home/runner/work/azul/azul/src/humancellatlas/data/metadata/helpers/staging_area.py", line 60, in __attrs_post_init__
    self._validator.validate_json(self.content, self.name)
  File "/home/runner/work/azul/azul/src/humancellatlas/data/metadata/helpers/schema_validation.py", line 34, in validate_json
    validate(file_json, schema, format_checker=FormatChecker())
  File "/home/runner/work/azul/azul/.venv/lib/python3.9/site-packages/jsonschema/validators.py", line 1119, in validate
    error = exceptions.best_match(validator.iter_errors(instance))
  File "/home/runner/work/azul/azul/.venv/lib/python3.9/site-packages/jsonschema/exceptions.py", line 384, in best_match
    best = next(errors, None)
  File "/home/runner/work/azul/azul/.venv/lib/python3.9/site-packages/jsonschema/validators.py", line 288, in iter_errors
    for error in errors:
  File "/home/runner/work/azul/azul/.venv/lib/python3.9/site-packages/jsonschema/_validators.py", line 332, in properties
    yield from validator.descend(
  File "/home/runner/work/azul/azul/.venv/lib/python3.9/site-packages/jsonschema/validators.py", line 305, in descend
    for error in self.evolve(schema=schema).iter_errors(instance):
  File "/home/runner/work/azul/azul/.venv/lib/python3.9/site-packages/jsonschema/validators.py", line 288, in iter_errors
    for error in errors:
  File "/home/runner/work/azul/azul/.venv/lib/python3.9/site-packages/jsonschema/_validators.py", line 294, in ref
    scope, resolved = validator.resolver.resolve(ref)
  File "/home/runner/work/azul/azul/.venv/lib/python3.9/site-packages/jsonschema/validators.py", line 898, in resolve
    return url, self._remote_cache(url)
  File "/home/runner/work/azul/azul/.venv/lib/python3.9/site-packages/jsonschema/validators.py", line 914, in resolve_from_url
    raise exceptions.RefResolutionError(exc)
jsonschema.exceptions.RefResolutionError: Expecting value: line 1 column 1 (char 0)

----------------------------------------------------------------------
Ran 394 tests in 1346.841s

FAILED (errors=1, skipped=4)
make: *** [Makefile:224: test] Error 1
Error: Process completed with exit code 2.
```

**Comment by hannes-ucsc** [comment] 2023-03-01 23:48
This issue and the related #4438 are about requests to the GitHub API. The stack traces @achave11 posts above refer to JSON schema validation (and one of the stack traces explicitly refers to `https://schema.staging.data.humancellatlas.org/`, so this must reflect an outage of the site where EBI hosts the schema. We should create a new ticket for that.

**Comment by achave11-ucsc** [comment] 2023-03-02 18:17
New ticket created #5022.

**Comment by hannes-ucsc** [comment] 2023-11-01 16:10
https://github.com/DataBiosphere/azul/actions/runs/6716191177/job/18252042002?pr=5669

**Comment by dsotirho-ucsc** [comment] 2023-11-01 18:44
@hannes-ucsc: "Resolve by cloning the schema_test_data repository instead of using GitHub REST API to fetch each file individually."

**Comment by hannes-ucsc** [comment] 2024-01-12 00:34
For demo, can a bundle from the usual canned staging area, just to ensure that these changes didn't break the canning script for that.

**Closed as completed** 2024-02-14 19:45 UTC
Labels: demoed, test, demo
