### ISSUE TITLE
Copy pre-generated matrices from DCP/1 to DCP/2

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#2463] opened 2020-11-17 20:39 UTC
Migrate CZI-controlled S3 buckets containing DCP/1 non-DSS data (project-level matrices) into UCSC-controlled buckets.
Partner ticket of #2459.

**Comment by theathorn** [comment] 2020-11-19 18:23
May be superseded by #2483.

**Comment by melainalegaspi** [comment] 2020-11-23 19:53
Duplicate of #2483

**Closed** 2020-11-23 19:53 UTC
Labels: data, orange, task
