### ISSUE TITLE
IT subtest catalog_complete fails on GitLab anvildev

### ISSUE THREAD

**Issue by dsotirho-ucsc** [DataBiosphere/azul#5200] opened 2023-05-10 23:44 UTC
The IT subtest `catalog_complete` failed on three consecutive attempts.

https://gitlab.anvil.gi.ucsc.edu/ucsc/azul/-/jobs/15545
https://gitlab.anvil.gi.ucsc.edu/ucsc/azul/-/jobs/15551
https://gitlab.anvil.gi.ucsc.edu/ucsc/azul/-/jobs/15554

The subtest appears to of been run with 435 bundles, however the `_get_entities` method specifies a size parameter of `100` when retrieving hits.

```
2023-05-10 22:20:28,655 INFO    MainThread: Message count history (most recent first) is [0, 0, 0, 0, 0, 0, 1, 3, 67, 742, 541, 563, 538, 641, 634, 713, 642, 560, 716, 839, 723, 582, 916, 793, 907, 883, 794, 911, 855, 889, 886, 968, 732, 950, 784, 847, 423, 466, 393, 293, 218, 218, 0].
2023-05-10 22:20:28,655 INFO    MainThread: The queues have emptied.
2023-05-10 22:20:28,656 INFO    MainThread: Beginning sub-test [catalog_complete] {'catalog': 'anvil-it'}
2023-05-10 22:20:28,675 DEBUG   MainThread: Expecting bundles [AnvilBundleFQID(uuid='5001caf5-d11f-ada1-8aee-9c01ab802561', version='2022-06-01T00:00:00.000000Z', source=SourceRef(id='0377b6a0-a203-46f3-a4e4-0238b21ce141', spec=TDRSourceSpec(prefix=Prefix(common='', partition=1), project='datarepo-1ba591a6', name='ANVIL_1000G_high_coverage_2019_20221019_ANV5_202303081523', is_snapshot=True)), entity_type=<BundleEntityType.primary: 'biosample'>), … 
2023-05-10 22:20:28,682 INFO    MainThread: GET https://service.anvil.gi.ucsc.edu/index/datasets?catalog=anvil-it&size=100&filters=%7B%7D ...
2023-05-10 22:20:29,969 INFO    MainThread: ... -> 200
2023-05-10 22:20:29,970 INFO    MainThread: Detected 100 of 435 bundles in 1 hits for entity type datasets on try #0.
2023-05-10 22:20:34,978 INFO    MainThread: GET https://service.anvil.gi.ucsc.edu/index/datasets?catalog=anvil-it&size=100&filters=%7B%7D ...
2023-05-10 22:20:35,087 INFO    MainThread: ... -> 200
2023-05-10 22:20:35,088 INFO    MainThread: Detected 100 of 435 bundles in 1 hits for entity type datasets on try #1.
2023-05-10 22:20:40,093 INFO    MainThread: GET https://service.anvil.gi.ucsc.edu/index/datasets?catalog=anvil-it&size=100&filters=%7B%7D ...
2023-05-10 22:20:40,168 INFO    MainThread: ... -> 200
2023-05-10 22:20:40,169 INFO    MainThread: Detected 100 of 435 bundles in 1 hits for entity type datasets on try #2.
2023-05-10 22:20:45,175 INFO    MainThread: GET https://service.anvil.gi.ucsc.edu/index/datasets?catalog=anvil-it&size=100&filters=%7B%7D ...
2023-05-10 22:20:45,249 INFO    MainThread: ... -> 200
2023-05-10 22:20:45,250 INFO    MainThread: Detected 100 of 435 bundles in 1 hits for entity type datasets on try #3.
2023-05-10 22:20:50,256 INFO    MainThread: GET https://service.anvil.gi.ucsc.edu/index/datasets?catalog=anvil-it&size=100&filters=%7B%7D ...
2023-05-10 22:20:50,345 INFO    MainThread: ... -> 200
2023-05-10 22:20:50,346 INFO    MainThread: Detected 100 of 435 bundles in 1 hits for entity type datasets on try #4.

…

2023-05-10 22:30:11,921 INFO    MainThread: GET https://service.anvil.gi.ucsc.edu/index/datasets?catalog=anvil-it&size=100&filters=%7B%7D ...
2023-05-10 22:30:11,993 INFO    MainThread: ... -> 200
2023-05-10 22:30:11,994 INFO    MainThread: Detected 100 of 435 bundles in 1 hits for entity type datasets on try #112.
2023-05-10 22:30:16,999 INFO    MainThread: GET https://service.anvil.gi.ucsc.edu/index/datasets?catalog=anvil-it&size=100&filters=%7B%7D ...
2023-05-10 22:30:17,080 INFO    MainThread: ... -> 200
2023-05-10 22:30:17,081 INFO    MainThread: Detected 100 of 435 bundles in 1 hits for entity type datasets on try #113.
2023-05-10 22:30:22,087 INFO    MainThread: GET https://service.anvil.gi.ucsc.edu/index/datasets?catalog=anvil-it&size=100&filters=%7B%7D ...
2023-05-10 22:30:22,174 INFO    MainThread: ... -> 200
2023-05-10 22:30:22,175 INFO    MainThread: Detected 100 of 435 bundles in 1 hits for entity type datasets on try #114.
2023-05-10 22:30:27,181 INFO    MainThread: GET https://service.anvil.gi.ucsc.edu/index/datasets?catalog=anvil-it&size=100&filters=%7B%7D ...
2023-05-10 22:30:27,261 INFO    MainThread: ... -> 200
2023-05-10 22:30:27,262 INFO    MainThread: Detected 100 of 435 bundles in 1 hits for entity type datasets on try #115.
2023-05-10 22:30:32,269 INFO    MainThread: GET https://service.anvil.gi.ucsc.edu/index/datasets?catalog=anvil-it&size=100&filters=%7B%7D ...
2023-05-10 22:30:32,341 INFO    MainThread: ... -> 200
2023-05-10 22:30:32,342 INFO    MainThread: Detected 100 of 435 bundles in 1 hits for entity type datasets on try #116.
2023-05-10 22:30:32,342 ERROR   MainThread: Only found 100 of 435 bundles in under 600 seconds.
2023-05-10 22:30:32,346 INFO    MainThread: Failed sub-test [catalog_complete] {'catalog': 'anvil-it'}
```

- [ ] Security design review completed; the Resolution of this issue does **not** …
  - [ ] … affect authentication; for example:
    - OAuth 2.0 with the application (API or Swagger UI)
    - Authentication of developers with Google Cloud APIs
    - Authentication of developers with AWS APIs
    - Authentication with a GitLab instance in the system
    - Password and 2FA authentication with GitHub
    - API access token authentication with GitHub
    - Authentication with 
  - [ ] … affect the permissions of internal users like access to
    - Cloud resources on AWS and GCP
    - GitLab repositories, projects and groups, administration
    - an EC2 instance via SSH
    - GitHub issues, pull requests, commits, commit statuses, wikis, repositories, organizations
  - [ ] … affect the permissions of external users like access to
    - TDR snapshots
  - [ ] … affect permissions of service or bot accounts
    - Cloud resources on AWS and GCP
  - [ ] … affect audit logging in the system, like
    - adding, removing or changing a log message that represents an auditable event
    - changing the routing of log messages through the system
  - [ ] … affect monitoring of the system
  - [ ] … introduce a new software dependency like
    - Python packages on PYPI
    - Command-line utilities
    - Docker images
    - Terraform providers
  - [ ] … add an interface that exposes sensitive or confidential data at the security boundary
  - [ ] … affect the encryption of data at rest
  - [ ] … require persistence of sensitive or confidential data that might require encryption at rest
  - [ ] … require unencrypted transmission of data within the security boundary
  - [ ] … affect the network security layer; for example by 
    - modifying, adding or removing firewall rules
    - modifying, adding or removing security groups
    - changing or adding a port a service, proxy or load balancer listens on
- [ ] Documentation on any unchecked boxes is provided in comments below

**Comment by nadove-ucsc** [comment] 2023-05-14 06:08
> however the _get_entities method specifies a size parameter of 100 when retrieving hits.

This is only the page size, not the total number of entities retrieved. For HCA catalogs, `_get_entities` makes requests to the `files` index; we certainly have more than 100 files indexed on HCA `dev` and `prod`, so this does not explain the failure.

**Comment by nadove-ucsc** [comment] 2023-05-14 10:15
I found the cause: 

https://github.com/DataBiosphere/azul/blob/70ecbfa11534da5737bbb5db81e3741c13fb1279/src/azul/indexer/index_service.py#L632

So this might be a dupe of https://github.com/DataBiosphere/azul/issues/3725

**Comment by dsotirho-ucsc** [comment] 2023-05-15 19:17
@hannes-ucsc: "Utilmately, we should use the bundles endpoint to determine, or approximate, the completeness of the index during IT. However, to expedite the fix, we will simply include `files` and `biosamples` when looking for bundles in AnVIL catalogs during IT. Addition of a `bundles` endpoint / index for AnVIL should be a separate ticket. A warning should be added above the line Noa links to. Another separate ticket should be filed for adding warnings when other accumulation limits are hit."

**Comment by nadove-ucsc** [comment] 2023-05-15 21:15
> Addition of a bundles endpoint / index for AnVIL should be a separate ticket.
https://github.com/DataBiosphere/azul/issues/5214

> Another separate ticket should be filed for adding warnings when other accumulation limits are hit.
https://github.com/DataBiosphere/azul/issues/5215

**Closed as completed** 2023-06-21 23:13 UTC
Labels: test, no demo, spike:2
