### ISSUE TITLE
Failed to generate file manifest

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#4402] opened 2022-08-23 18:11 UTC
[Slack thread](https://humancellatlas.slack.com/archives/C015FPVADC1/p1661277120983219):
```
Mark Diekhans, Aug 23, 2022, 13:51
https://data.humancellatlas.org/explore/projects?filter=%5B%7B%22facetName%22:%22libraryConstructionApproach%22,%22terms%22:%5B%22Smart-seq2%22%5D%7D%5D
Export Selected Data -> Request File Manifest
select Mus musculus, Homo sapiens, and Unspecified
select bam
Prepare Manifest
Request URL
https://service.azul.data.humancellatlas.org/fetch/manifest/files?token=eyJleGVjdXRpb25faWQiOiAiOGNkMzU1ZTEtMDA4Mi00ODcxLTkzNTEtN2FlNmRhMWRkYjhjIiwgInJlcXVlc3RfaW5kZXgiOiA1LCAid2FpdF90aW1lIjogMTB9
Error Message
Traceback (most recent call last):
 File "/var/task/chalice/app.py", line 1752, in _get_view_function_response
   response = view_function(**function_args)
 File "/var/task/app.py", line 1566, in fetch_file_manifest
   return _file_manifest(fetch=True)
 File "/var/task/app.py", line 1586, in _file_manifest
   return app.manifest_controller.get_manifest_async(self_url=app.self_url,
 File "/var/task/azul/service/manifest_controller.py", line 158, in get_manifest_async
   token_or_state = self.async_service.inspect_generation(token)
 File "/var/task/azul/service/async_manifest_service.py", line 100, in inspect_generation
   raise StateMachineError(status, output)
azul.service.async_manifest_service.StateMachineError: ('Failed to generate manifest', 'FAILED', None)
------------------
Submitted from: https://data.humancellatlas.org/.
Ticket url:broadinstitute.zendesk.com/agent/tickets/293737
```

**Comment by theathorn** [comment] 2022-08-23 18:13
William Sullivan reported a similar attempt with the same back trace: "Selected Smart-Seq2 projects should be 40, export selected data, file manifest, all species, select all files, get manifest then spins for a while and throws error".

**Comment by melainalegaspi** [comment] 2022-08-23 19:54
@hannes-ucsc :"First we need to spike this in order to establish whether this is covered by an existing ticket. I suspect it is by covered by the ticket about manifests that are too large failing to generate. For example, #3778. We should also consider preventing users to request manifests that are too large until we have a better solution for large manifests."

**Comment by diekhans** [comment] 2022-08-23 19:57
Yes, Will is working with me.

What is needed TODAY is the basic metadata for these 40 samples.  If you can suggest a way to get this without spending a ton of time downloading each sample ,that would be great.

**Comment by theathorn** [comment] 2022-08-23 20:57
You are going to need to do this one project at a time. If you make the "Smart-seq2" selection you will see a list of 40 projects. Then click on the "Metadata" download icon for each project in turn.

**Comment by diekhans** [comment] 2022-08-23 21:09
Azul owes me a beer

**Comment by hannes-ucsc** [comment] 2022-08-23 23:58
Splitting it up won't work as it is not caused by size. This is a dupe of #4261. I'll leave this one open as a blocked ticket because it is for `prod` and has the participation of people in need of hydration.

Logs from `prod`

**CloudWatch Logs Insights**  
region: us-east-1  
log-group-names: /aws/lambda/azul-service-prod-manifest  
start-time: 2022-08-23T17:41:35.769Z  
end-time: 2022-08-23T17:43:32.566Z  
query-string:
```
fields @timestamp, @message
# | filter @requestId = '50869494-ff3a-4784-893c-0ab7053688b9'
| filter @logStream = '2022/08/23/[$LATEST]f39d4796bca4406a88150e9563db22ac'
| sort @timestamp desc
| limit 20
```
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
|       @timestamp        |                                                                                                                                                                                                                                                                                                                                                                                                                                                                              @message                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
|-------------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| 2022-08-23 17:42:41.970 | END RequestId: 50869494-ff3a-4784-893c-0ab7053688b9                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
| 2022-08-23 17:42:41.970 | REPORT RequestId: 50869494-ff3a-4784-893c-0ab7053688b9 Duration: 19274.04 ms Billed Duration: 19275 ms Memory Size: 2048 MB Max Memory Used: 264 MB                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
| 2022-08-23 17:42:41.968 | [ERROR] TypeError: unhashable type: 'list' Traceback (most recent call last):   File "/var/task/chalice/app.py", line 1601, in __call__     return self.handler(event_obj)   File "/var/task/chalice/app.py", line 1563, in __call__     return self.handler(request, self.next_handler)   File "/var/task/azul/chalice.py", line 110, in _lambda_context_middleware     return get_response(event)   File "/var/task/chalice/app.py", line 1554, in __call__     return self._original_func(event.to_dict(), event.context)   File "/var/task/app.py", line 1597, in generate_manifest     return app.manifest_controller.get_manifest(event)   File "/var/task/azul/service/manifest_controller.py", line 90, in get_manifest     self.partition_state_key: result.to_json()   File "/var/task/azul/service/manifest_service.py", line 275, in to_json     return attr.asdict(self)   File "/opt/python/attr/_funcs.py", line 67, in asdict     rv[a.name] = df( |
| 2022-08-23 17:42:40.185 | [INFO] 2022-08-23T17:42:40.184Z 00010ca1-b0ba-466f-8c58-dabbad000000 elasticsearch POST https://search-azul-index-prod-mjluewlvxikvhillefxotw2tbm.us-east-1.es.amazonaws.com:443/azul_v2_prod_dcp19_files_aggregate/_search [status:200 request:0.143s]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
| 2022-08-23 17:42:39.018 | [INFO] 2022-08-23T17:42:39.018Z 00010ca1-b0ba-466f-8c58-dabbad000000 elasticsearch POST https://search-azul-index-prod-mjluewlvxikvhillefxotw2tbm.us-east-1.es.amazonaws.com:443/azul_v2_prod_dcp19_files_aggregate/_search [status:200 request:0.140s]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
| 2022-08-23 17:42:37.861 | [INFO] 2022-08-23T17:42:37.861Z 00010ca1-b0ba-466f-8c58-dabbad000000 elasticsearch POST https://search-azul-index-prod-mjluewlvxikvhillefxotw2tbm.us-east-1.es.amazonaws.com:443/azul_v2_prod_dcp19_files_aggregate/_search [status:200 request:0.134s]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
| 2022-08-23 17:42:36.717 | [INFO] 2022-08-23T17:42:36.717Z 00010ca1-b0ba-466f-8c58-dabbad000000 elasticsearch POST https://search-azul-index-prod-mjluewlvxikvhillefxotw2tbm.us-east-1.es.amazonaws.com:443/azul_v2_prod_dcp19_files_aggregate/_search [status:200 request:0.132s]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
| 2022-08-23 17:42:35.577 | [INFO] 2022-08-23T17:42:35.577Z 00010ca1-b0ba-466f-8c58-dabbad000000 elasticsearch POST https://search-azul-index-prod-mjluewlvxikvhillefxotw2tbm.us-east-1.es.amazonaws.com:443/azul_v2_prod_dcp19_files_aggregate/_search [status:200 request:0.134s]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
| 2022-08-23 17:42:34.443 | [INFO] 2022-08-23T17:42:34.443Z 00010ca1-b0ba-466f-8c58-dabbad000000 elasticsearch POST https://search-azul-index-prod-mjluewlvxikvhillefxotw2tbm.us-east-1.es.amazonaws.com:443/azul_v2_prod_dcp19_files_aggregate/_search [status:200 request:0.129s]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
| 2022-08-23 17:42:33.331 | [INFO] 2022-08-23T17:42:33.331Z 00010ca1-b0ba-466f-8c58-dabbad000000 elasticsearch POST https://search-azul-index-prod-mjluewlvxikvhillefxotw2tbm.us-east-1.es.amazonaws.com:443/azul_v2_prod_dcp19_files_aggregate/_search [status:200 request:0.140s]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
| 2022-08-23 17:42:32.195 | [INFO] 2022-08-23T17:42:32.195Z 00010ca1-b0ba-466f-8c58-dabbad000000 elasticsearch POST https://search-azul-index-prod-mjluewlvxikvhillefxotw2tbm.us-east-1.es.amazonaws.com:443/azul_v2_prod_dcp19_files_aggregate/_search [status:200 request:0.143s]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
| 2022-08-23 17:42:31.055 | [INFO] 2022-08-23T17:42:31.055Z 00010ca1-b0ba-466f-8c58-dabbad000000 elasticsearch POST https://search-azul-index-prod-mjluewlvxikvhillefxotw2tbm.us-east-1.es.amazonaws.com:443/azul_v2_prod_dcp19_files_aggregate/_search [status:200 request:0.138s]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
| 2022-08-23 17:42:29.880 | [INFO] 2022-08-23T17:42:29.880Z 00010ca1-b0ba-466f-8c58-dabbad000000 elasticsearch POST https://search-azul-index-prod-mjluewlvxikvhillefxotw2tbm.us-east-1.es.amazonaws.com:443/azul_v2_prod_dcp19_files_aggregate/_search [status:200 request:0.138s]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
| 2022-08-23 17:42:28.826 | [INFO] 2022-08-23T17:42:28.826Z 00010ca1-b0ba-466f-8c58-dabbad000000 elasticsearch POST https://search-azul-index-prod-mjluewlvxikvhillefxotw2tbm.us-east-1.es.amazonaws.com:443/azul_v2_prod_dcp19_files_aggregate/_search [status:200 request:0.139s]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
| 2022-08-23 17:42:27.651 | [INFO] 2022-08-23T17:42:27.651Z 00010ca1-b0ba-466f-8c58-dabbad000000 elasticsearch POST https://search-azul-index-prod-mjluewlvxikvhillefxotw2tbm.us-east-1.es.amazonaws.com:443/azul_v2_prod_dcp19_files_aggregate/_search [status:200 request:0.137s]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
| 2022-08-23 17:42:26.491 | [INFO] 2022-08-23T17:42:26.491Z 00010ca1-b0ba-466f-8c58-dabbad000000 elasticsearch POST https://search-azul-index-prod-mjluewlvxikvhillefxotw2tbm.us-east-1.es.amazonaws.com:443/azul_v2_prod_dcp19_files_aggregate/_search [status:200 request:0.175s]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
| 2022-08-23 17:42:25.294 | [INFO] 2022-08-23T17:42:25.294Z 00010ca1-b0ba-466f-8c58-dabbad000000 elasticsearch POST https://search-azul-index-prod-mjluewlvxikvhillefxotw2tbm.us-east-1.es.amazonaws.com:443/azul_v2_prod_dcp19_files_aggregate/_search [status:200 request:0.152s]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
| 2022-08-23 17:42:24.094 | [INFO] 2022-08-23T17:42:24.094Z 00010ca1-b0ba-466f-8c58-dabbad000000 elasticsearch POST https://search-azul-index-prod-mjluewlvxikvhillefxotw2tbm.us-east-1.es.amazonaws.com:443/azul_v2_prod_dcp19_files_aggregate/_search [status:200 request:0.156s]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
| 2022-08-23 17:42:22.932 | [INFO] 2022-08-23T17:42:22.931Z 00010ca1-b0ba-466f-8c58-dabbad000000 elasticsearch POST https://search-azul-index-prod-mjluewlvxikvhillefxotw2tbm.us-east-1.es.amazonaws.com:443/azul_v2_prod_dcp19_files_aggregate/_search [status:200 request:0.142s]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
| 2022-08-23 17:42:22.739 | [INFO] 2022-08-23T17:42:22.738Z 00010ca1-b0ba-466f-8c58-dabbad000000 azul.service.manifest_service Cached manifest not found: manifests/1f1a58cd-a224-5dd5-b68d-d6a820b376d1.c26ed8f9-97fb-5fc1-9211-d05e787b64c0.tsv                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

**Comment by hannes-ucsc** [comment] 2022-08-24 16:22
Turns out it is caused by size. Any manifest bigger than 50 MiB will fail like this, so splitting a manifest is a functioning workaround as long as the parts don't exceed 50 MiB in size.

**Comment by melainalegaspi** [comment] 2022-08-24 18:46
@hannes-ucsc to ask for verification by user when blocker lands in prod.

**Comment by hannes-ucsc** [comment] 2022-08-26 18:25
The fix landed in prod and I confirmed it to be effective.

**Comment by hannes-ucsc** [comment] 2022-08-26 18:27
Feel free to reopen if you have a different experience, @diekhans.

I'll demo the underlying #4261, instead.

**Closed by hannes-ucsc** 2022-08-26 18:27 UTC
Labels: bug, orange, no demo, manifests

**Comment by diekhans** [comment] 2022-08-26 18:46
it worked!! thanks
