### ISSUE TITLE
Many config attributes/properties are uncovered

### ISSUE THREAD

**Issue by jessebrennan** [DataBiosphere/azul#3162] opened 2021-06-21 22:44 UTC
Covering these could be a simple loop through `dir(config)` or something similar. Covering these attributes would reveal errors in our configuration along with any attributes that are no longer used and should be removed.

Coverage report for config from latest dev build https://codecov.io/gh/DataBiosphere/azul/src/dcec391f8ad5e3e207d0e3fa6ac67923141c2f70/src/azul/__init__.py

One potential problem with covering these is that intentionally unset config variables (like `grafana_endpoint` when monitoring is disabled) may change between deployments and will complicate testing.

**Comment by jessebrennan** [comment] 2021-06-21 22:46
In retrospect, I'm not sure this would be worth the invested effort, but triage can decide :shrug:

**Comment by melainalegaspi** [comment] 2021-06-22 18:53
@hannes-ucsc to triage.

**Comment by melainalegaspi** [comment] 2021-09-07 18:58
Closing as duplicate of #3404.

**Closed by melainalegaspi** 2021-09-07 18:58 UTC
Labels: debt, test, orange, spike:1
