### ISSUE TITLE
Bundle 9d0f5cd1-0ef6-5eed-8dd7-f15d36a34185 fails during reindex

### ISSUE THREAD

**Issue by noah-aviel-dove** [DataBiosphere/azul#2916] opened 2021-03-23 09:39 UTC
In addition to the 4 expected failed bundles, there was one unexpected failure during the reindex for https://github.com/DataBiosphere/azul/issues/2841: 

```
$ cat azul-notifications_fail-dev.json | grep bundle_uuid
                        "bundle_uuid": "40733888-3b9f-500e-84fd-1a18a64aadbe",
                        "bundle_uuid": "94565940-7b2f-5fd7-beb1-dc309687fe09",
                        "bundle_uuid": "9d0f5cd1-0ef6-5eed-8dd7-f15d36a34185",
                        "bundle_uuid": "ae338c4e-650f-545b-8631-3c8d755aa2f9",
                        "bundle_uuid": "c12a6ca2-3234-5182-ad0b-f8c2fb881ab5",
```

`9d0f5cd1-0ef6-5eed-8dd7-f15d36a34185` is the only bundle not outlined as an expected failure in the operator manual.

**Comment by amarjandu** [comment] 2021-03-23 15:58
```
ae338c4e-650f-545b-8631-3c8d755aa2f9
c12a6ca2-3234-5182-ad0b-f8c2fb881ab5
40733888-3b9f-500e-84fd-1a18a64aadbe
9d0f5cd1-0ef6-5eed-8dd7-f15d36a34185
```
These subgraphs are tracked by  https://github.com/DataBiosphere/azul/issues/2873

------------------------------------
```
94565940-7b2f-5fd7-beb1-dc309687fe09
```
This subgraph is tracked by https://github.com/DataBiosphere/azul/issues/2870

**Comment by melainalegaspi** [comment] 2021-03-23 19:00
Closing, duplicate of #2870

**Closed by melainalegaspi** 2021-03-23 19:00 UTC
Labels: duplicate, orange
