### ISSUE TITLE
Index supplementary files for AnVIL

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#5000] opened 2023-02-21 17:34 UTC
We'll support this by adding a second type of bundle entity, `supplementary_file`, in addition to the current `biosample`.

Modify `azul.plugins.repository.tdr_anvil.Plugin._list_bundles` to run a second query that lists all `anvil_file` table rows with `is_supplementary` set and a `datarepo_row_id` matching the subgraph prefix. Each file row in the result set of the 2nd query represents a special subgraph. Note the bundle entity type in each BundleFQID instances that is returned, so that `fetch_bundle` knows what to do.

I'm a little fuzzy on the specifics of how supplementary files could be linked to other files. Will need a spike to study that. Then we can lay out a plan for `fetch_bundle`.

Update: The spike and discussions with the Broad resulted in the observation that files derived from supplementary files are also marked as supplementary files. This actually means that we don't even need to do a graph traversal. `fetch_bundle` will simply fetch the `file` row referenced in the BundleFQID of the notification, the dataset row for the dataset referenced by that file, and prepare a subgraph of two entities, the supplementary file and the dataset. We'll ignore any down- or upstream activities since they have no intrinsic metadata that describe any biological or experimental facts. They are mere join table rows that the TDR importer already traversed when marking files as supplementary. The metadata plugin should produce two contributions, one for the dataset and one for the file. If we produce bundle contributions in AnVIL, (I forget if we do), a 3rd one for bundles should be produced, too.

**Comment by dsotirho-ucsc** [comment] 2023-02-22 19:54
Assignee to fill in details.

**Comment by hannes-ucsc** [comment] 2023-03-02 00:40
Spike to 

1) find examples of a supplementary file row
2) exhaustively determine what other types of entities a supplementary file row could be connected to (presumable only downstream ones)
3) find example rows for entities derived from supplementary files

The aim is to understand what queries `fetch_bundle` would have to issue in order to traverse each supplementary file subgraph.

**Comment by nadove-ucsc** [comment] 2023-03-02 23:13
Looks like about 2/3 of the GTEx files are supplementary:

```
SELECT is_supplementary, count(*) as file_count
FROM `datarepo-1b7b0df4.ANVIL_GTEx_V8_hg38_20221013_ANV5_202303010031.anvil_file`
GROUP BY is_supplementary
```

```
[{
  "is_supplementary": "false",
  "file_count": "40156"
}, {
  "is_supplementary": "true",
  "file_count": "82844"
}]
```

**Comment by nadove-ucsc** [comment] 2023-03-02 23:14
An example is 
```
[{
  "file_id": "77aae608-9b4d-4ded-a413-af96d023d617"
}]
```

**Comment by nadove-ucsc** [comment] 2023-03-02 23:33
Here is an exhaustive breakdown of foreign keys that references the supplementary files for the V5 AnVIL snapshots. It appears that supplementary files can occur as inputs or outputs of generic `activity` entities. 

`datarepo-1b7b0df4.ANVIL_GTEx_V8_hg38_20221013_ANV5_202303010031`:
```
[{
  "table_name": "activity",
  "column_name": "generated_file_id",
  "link_count": "1543"
}, {
  "table_name": "activity",
  "column_name": "used_file_id",
  "link_count": "1543"
}]
```

`datarepo-199c9225.ANVIL_1000G_high_coverage_2019_20221019_ANV5_202302282132`:
```
[{
  "table_name": "activity",
  "column_name": "used_file_id",
  "link_count": "250"
}, {
  "table_name": "activity",
  "column_name": "generated_file_id",
  "link_count": "3455"
}]
```

There were no results for any of the other 9 snapshots.

Query to reproduce:
```
SELECT 
  table_name, 
  column_name, 
  COUNT(*) AS link_count
FROM 
(
    SELECT file_id 
    FROM `datarepo-d635d009.ANVIL_CMG_UWash_GRU_IRB_20221020_ANV5_202302282128.anvil_file`
    WHERE is_supplementary
) AS F, 
(
  SELECT 
    'activity' AS table_name, 
    'used_file_id' AS column_name,
    link
  FROM `datarepo-d635d009.ANVIL_CMG_UWash_GRU_IRB_20221020_ANV5_202302282128.anvil_activity`, 
  UNNEST(used_file_id) AS link
  UNION ALL 
  SELECT 
    'activity' AS table_name, 
    'generated_file_id' AS column_name,
    link
  FROM `datarepo-d635d009.ANVIL_CMG_UWash_GRU_IRB_20221020_ANV5_202302282128.anvil_activity`,
      UNNEST(generated_file_id) AS link
  UNION ALL
  SELECT 
    'alignmentactivity' AS table_name, 
    'used_file_id' AS column_name,
    link
  FROM `datarepo-d635d009.ANVIL_CMG_UWash_GRU_IRB_20221020_ANV5_202302282128.anvil_alignmentactivity`,
  UNNEST(used_file_id) AS link
  UNION ALL 
  SELECT 
    'alignmentactivity' AS table_name, 
    'generated_file_id' AS column_name,
    link
  FROM `datarepo-d635d009.ANVIL_CMG_UWash_GRU_IRB_20221020_ANV5_202302282128.anvil_alignmentactivity`,
  UNNEST(generated_file_id) AS link
  UNION ALL
  SELECT 
    'assayactivity' AS table_name, 
    'generated_file_id' AS column_name,
    link
  FROM `datarepo-d635d009.ANVIL_CMG_UWash_GRU_IRB_20221020_ANV5_202302282128.anvil_assayactivity`,
UNNEST(generated_file_id) AS link
  UNION ALL
  SELECT 
    'sequencingactivity' AS table_name, 
    'generated_file_id' AS column_name,
    link
  FROM `datarepo-d635d009.ANVIL_CMG_UWash_GRU_IRB_20221020_ANV5_202302282128.anvil_sequencingactivity`,
  UNNEST(generated_file_id) AS link
  UNION ALL
  SELECT 
    'variantcallingactivity' AS table_name, 
    'used_file_id' AS column_name,
    link
  FROM `datarepo-d635d009.ANVIL_CMG_UWash_GRU_IRB_20221020_ANV5_202302282128.anvil_variantcallingactivity`,
  UNNEST(used_file_id) AS link
  UNION ALL
  SELECT 
    'variantcallingactivity' AS table_name, 
    'generated_file_id' AS column_name,
    link
  FROM `datarepo-d635d009.ANVIL_CMG_UWash_GRU_IRB_20221020_ANV5_202302282128.anvil_variantcallingactivity`,
  UNNEST(generated_file_id) AS link
) AS L
WHERE F.file_id = L.link
GROUP BY L.table_name, L.column_name
```

List of foreign keys referencing the `file` table retrieved from `https://github.com/broadinstitute/anvil_tdr_ingest/blob/3579b8aa123ac117c9d0bd73e64e17701d4b975e/anvil_schema/schema/mapping_schema_object.json`

**Comment by achave11-ucsc** [comment] 2023-03-03 19:43
@hannes-ucsc: "Continue spike to find out if files derived from supplementary files are also marked as supplementary."

**Comment by nadove-ucsc** [comment] 2023-03-03 21:45
Every file that is derived from a file that is marked as supplementary file is itself marked as supplementary.

**Comment by nadove-ucsc** [comment] 2023-03-03 22:00
Some files that are marked as supplementary are derived from files that are not marked as supplementary.

**Comment by nadove-ucsc** [comment] 2023-03-03 22:03
Here is a breakdown of file-to-file derivations in the two snapshots that contain linked supplementary files. Activities with more than one input or output file are counted multiple times.

`datarepo-1b7b0df4.ANVIL_GTEx_V8_hg38_20221013_ANV5_202303010031`:

```
[{
  "link_count": "19240",
  "input_is_supplementary": "false",
  "output_is_supplementary": "false"
}, {
  "link_count": "1543",
  "input_is_supplementary": "true",
  "output_is_supplementary": "true"
}]
```

`datarepo-199c9225.ANVIL_1000G_high_coverage_2019_20221019_ANV5_202302282132`:

```
[{
  "link_count": "16007",
  "input_is_supplementary": "false",
  "output_is_supplementary": "false"
}, {
  "link_count": "3205",
  "input_is_supplementary": "false",
  "output_is_supplementary": "true"
}, {
  "link_count": "250",
  "input_is_supplementary": "true",
  "output_is_supplementary": "true"
}]
```

Query used:

```
WITH activity_links AS (
  SELECT input_id, output_id
  FROM  
    `datarepo-1b7b0df4.ANVIL_GTEx_V8_hg38_20221013_ANV5_202303010031.anvil_activity`,
    UNNEST(used_file_id) AS input_id,
    UNNEST(generated_file_id) AS output_id
)
SELECT 
  COUNT(*) AS link_count, 
  fi.is_supplementary AS input_is_supplementary,
  fo.is_supplementary AS output_is_supplementary
FROM 
  activity_links, 
  `datarepo-1b7b0df4.ANVIL_GTEx_V8_hg38_20221013_ANV5_202303010031.anvil_file` AS fi,
  `datarepo-1b7b0df4.ANVIL_GTEx_V8_hg38_20221013_ANV5_202303010031.anvil_file` AS fo
WHERE 
  activity_links.input_id = fi.file_id AND
  activity_links.output_id = fo.file_id
GROUP BY
  fi.is_supplementary,
  fo.is_supplementary
```

**Comment by achave11-ucsc** [comment] 2023-03-06 19:48
@hannes-ucsc: "Spike to continue to pick an example of a file marked as supplementary derived from a file that is not."

**Comment by nadove-ucsc** [comment] 2023-03-06 22:49
Here is such an example:
```
[{
  "input_id": "6972c433-e4e9-468f-b0c5-304b429d2265",
  "output_id": "1f50bf7f-aee0-42f7-ad57-c7124fb9da11",
  "activity_id": "2fa4ad8e-e8a7-6c06-7b87-f3f311bc86b2"
}]
```

```
SELECT input_id, output_id, activity_id
FROM  
  `datarepo-199c9225.ANVIL_1000G_high_coverage_2019_20221019_ANV5_202302282132.anvil_activity`,
  UNNEST(used_file_id) AS input_id,
  UNNEST(generated_file_id) AS output_id,
  `datarepo-199c9225.ANVIL_1000G_high_coverage_2019_20221019_ANV5_202302282132.anvil_file` AS fi,
  `datarepo-199c9225.ANVIL_1000G_high_coverage_2019_20221019_ANV5_202302282132.anvil_file` AS fo
WHERE 
  input_id = fi.file_id AND
  output_id = fo.file_id AND
  NOT fi.is_supplementary AND 
  fo.is_supplementary
LIMIT 1
```

**Comment by achave11-ucsc** [comment] 2023-03-07 19:39
Assignee to accommodate derived supplementary files in design.

**Comment by theathorn** [comment] 2023-03-09 01:15
11 updated schema v5 snapshots in rows 49-59 of the  "[AnVIL Prod](https://docs.google.com/spreadsheets/d/1yYiB3TrX0wvLCHvtWY1GTZZcAf5MmMREgn52OKCHsqs/edit?pli=1#gid=187179274)" tab.

**Comment by hannes-ucsc** [comment] 2023-03-09 17:43
> Assignee to accommodate derived supplementary files in design.

Done

**Comment by hannes-ucsc** [comment] 2023-03-09 17:52
> Assignee to accommodate derived supplementary files in design.

That should be a separate ticket: #5037

**Comment by achave11-ucsc** [comment] 2023-03-09 19:49
Assignee to specify which contributions the supplementary file subgraph should produce.

**Comment by hannes-ucsc** [comment] 2023-03-10 01:49
Done. A bit sloppy but I think @noah-aviel-dove should be able to make sense of it.

**Comment by hannes-ucsc** [comment] 2023-05-05 05:24
For demo, show the added supplementary files in service response and DB UI. Show `is_supplementary` in response `hits` and `termFacets`. Show filtering by that facet.

**Closed as completed** 2023-06-21 23:07 UTC
Labels: demoed, API, spike:3, demo, indexer
