### ISSUE TITLE
/repository/files/summary is failing on dev

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/azul#353] opened 2018-09-26 16:10 UTC
https://service.dev.explore.data.humancellatlas.org/repository/files/summary?filters=%7B%7D

Traceback (most recent call last):
File "/var/task/chalice/app.py", line 726, in _get_view_function_response
response = view_function(**function_args)
File "/var/task/app.py", line 136, in get_data
filters['file']['fileId'] = {"is": [file_id]}
KeyError: 'file'

**Comment by hannes-ucsc** [comment] 2018-09-26 16:12
Duplicate of #354

**Closed by hannes-ucsc** 2018-09-26 16:12 UTC
