### ISSUE TITLE
Failure to access snapshots during IT

### ISSUE THREAD

**Issue by amarjandu** [DataBiosphere/azul#3626] opened 2021-11-09 18:14 UTC
https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/33186

```python
======================================================================
ERROR: test_can_bundle_configured_catalogs (integration_test.CanBundleScriptIntegrationTest) (catalog='it2', repository=Config.Catalog.Plugin(name='tdr'))
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builds/ucsc/azul/test/integration_test.py", line 1250, in test_can_bundle_configured_catalogs
    self._test_catalog(catalog)
  File "/builds/ucsc/azul/test/integration_test.py", line 1211, in _test_catalog
    self._can_bundle(source=str(fqid.source.spec),
  File "/builds/ucsc/azul/test/integration_test.py", line 1287, in _can_bundle
    return self._can_bundle_main(args)
  File "/builds/ucsc/azul/scripts/can_bundle.py", line 63, in main
    bundle = fetch_bundle(args.source, args.uuid, args.version)
  File "/builds/ucsc/azul/scripts/can_bundle.py", line 77, in fetch_bundle
    configured_source = plugin.resolve_source(configured_source)
  File "/builds/ucsc/azul/src/azul/plugins/__init__.py", line 242, in resolve_source
    id = self.lookup_source_id(spec)
  File "/builds/ucsc/azul/src/azul/plugins/repository/tdr/__init__.py", line 229, in lookup_source_id
    return self.tdr.lookup_source(spec).id
  File "/builds/ucsc/azul/src/azul/terra.py", line 421, in lookup_source
    source = self._lookup_source(source_spec)
  File "/builds/ucsc/azul/src/azul/terra.py", line 453, in _lookup_source
    require(response.status == 200,
  File "/builds/ucsc/azul/src/azul/__init__.py", line 1206, in require
    reject(not condition, *args, exception=exception)
  File "/builds/ucsc/azul/src/azul/__init__.py", line 1225, in reject
    raise exception(*args)
azul.RequirementError: Failed to access snapshot 'hca_dev_38449aea70b540db84b31e08f32efe34__20210830_20210903' via the TDR API after resolving its ID to 'cabce9f2-b98b-49f3-9dd4-d7e14c19acd2'
======================================================================
ERROR: test_indexing (integration_test.IndexingIntegrationTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builds/ucsc/azul/test/azul_test_case.py", line 154, in wrapped
    return method(*args, **kwargs)
  File "/builds/ucsc/azul/test/integration_test.py", line 330, in test_indexing
    catalogs: List[Catalog] = [
  File "/builds/ucsc/azul/test/integration_test.py", line 332, in <listcomp>
    notifications=self._prepare_notifications(catalog) if index else {})
  File "/builds/ucsc/azul/test/integration_test.py", line 710, in _prepare_notifications
    bundle_fqids = self._list_bundles(catalog, max_bundles=self.max_bundles)
  File "/builds/ucsc/azul/test/integration_test.py", line 827, in _list_bundles
    bundle_fqids = super()._list_bundles(catalog, num_bundles)
  File "/builds/ucsc/azul/test/integration_test.py", line 237, in _list_bundles
    bundle_fqids = reservoir_sample(max_bundles, bundle_fqids, random=self.random)
  File "/builds/ucsc/azul/src/azul/iterators.py", line 48, in reservoir_sample
    for i, item in enumerate(it, start=k + 1):
  File "/builds/ucsc/azul/test/integration_test.py", line 229, in <genexpr>
    self.azul_client.list_bundles(catalog, source, prefix(source))
  File "/builds/ucsc/azul/test/integration_test.py", line 222, in prefix
    source = plugin.resolve_source(source)
  File "/builds/ucsc/azul/src/azul/plugins/__init__.py", line 242, in resolve_source
    id = self.lookup_source_id(spec)
  File "/builds/ucsc/azul/src/azul/plugins/repository/tdr/__init__.py", line 229, in lookup_source_id
    return self.tdr.lookup_source(spec).id
  File "/builds/ucsc/azul/src/azul/terra.py", line 421, in lookup_source
    source = self._lookup_source(source_spec)
  File "/builds/ucsc/azul/src/azul/terra.py", line 453, in _lookup_source
    require(response.status == 200,
  File "/builds/ucsc/azul/src/azul/__init__.py", line 1206, in require
    reject(not condition, *args, exception=exception)
  File "/builds/ucsc/azul/src/azul/__init__.py", line 1225, in reject
    raise exception(*args)
azul.RequirementError: Failed to access snapshot 'hca_dev_b4a7d12f6c2f40a39e359756997857e3__20210831_20210903' via the TDR API after resolving its ID to 'a36cb7cb-0122-40af-8942-1d5ec9372e77'
----------------------------------------------------------------------
Ran 16 tests in 146.821s
FAILED (errors=2, skipped=4)
```

**Comment by amarjandu** [comment] 2021-11-09 18:17
Might be a transient error, `_select dev && make post_deploy` indicates that the client has access to the snapshots.
```bash
2021-11-09 10:12:42,142 DEBUG   ThreadPoolExecutor-0_8: _request(…) -> b'{"id":"a36cb7cb-0122-40af-8942-1d5ec9372e77","name":"hca_dev_b4a7d12f6c2f40a39e359756997857e3__20210831_20210903","description":"Create snapshot hca_dev_b4a7d12f6c2f40a39e359756997857e3__20210831_20210903","createdDate":"2021-09-03T21:45:21.794948Z","so...'
2021-11-09 10:12:42,142 INFO    ThreadPoolExecutor-0_8: TDR client is authorized for API access to tdr:datarepo-dev-b2004d1c:snapshot/hca_dev_b4a7d12f6c2f40a39e359756997857e3__20210831_20210903:/0.
...
2021-11-09 10:12:50,673 DEBUG   ThreadPoolExecutor-0_14: _request(…) -> b'{"id":"cabce9f2-b98b-49f3-9dd4-d7e14c19acd2","name":"hca_dev_38449aea70b540db84b31e08f32efe34__20210830_20210903","description":"Create snapshot hca_dev_38449aea70b540db84b31e08f32efe34__20210830_20210903","createdDate":"2021-09-03T21:03:58.713703Z","so...'
2021-11-09 10:12:50,674 INFO    ThreadPoolExecutor-0_14: TDR client is authorized for API access to tdr:datarepo-dev-ac6efd3f:snapshot/hca_dev_38449aea70b540db84b31e08f32efe34__20210830_20210903:/0.
...

```

**Comment by melainalegaspi** [comment] 2021-11-09 19:46
Spike to investigate.

**Comment by noah-aviel-dove** [comment] 2021-11-16 02:18
Unable to reproduce. Since we were able to list the snapshot and resolve its ID, I don't think there's any evidence here of a permissions or configuration issue on our end. It's difficult to investigate since the error message doesn't include any information on the unexpected response we got back from TDR; all we know is that the status wasn't 200. My best guess is that it was some kind of transient 5xx error. To resolve this ticket, I suggest that we include more information when we raise this error:

```diff
Index: src/azul/terra.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/src/azul/terra.py b/src/azul/terra.py
--- a/src/azul/terra.py	(revision 8cacaf5436a0b8b37a0e23bd352c84ac74198963)
+++ b/src/azul/terra.py	(date 1637029063244)
@@ -451,7 +451,8 @@
             endpoint = self._repository_endpoint(tdr_path, snapshot_id)
             response = self._request('GET', endpoint)
             require(response.status == 200,
-                    f'Failed to access {resource} after resolving its ID to {snapshot_id!r}')
+                    f'Failed to access {resource} after resolving its ID to {snapshot_id!r}',
+                    response.status, response.data)
             return json.loads(response.data)
         else:
             raise RequirementError('Ambiguous response from TDR API', endpoint, response)
```

**Comment by melainalegaspi** [comment] 2021-11-16 19:57
@noah-aviel-dove to create follow-up ticket, then we'll close this as non-reproducible.

**Comment by noah-aviel-dove** [comment] 2021-11-16 19:59
https://github.com/DataBiosphere/azul/issues/3643

**Closed** 2021-11-16 20:01 UTC
Labels: bug, wontfix, test, orange, spike:1
