### ISSUE TITLE
Pin transitive dependencies

### ISSUE THREAD

**Issue by jessebrennan** [DataBiosphere/azul#1738] opened 2020-04-28 22:56 UTC
The dependencies lambda layer is content addressed by the hash of the `requirements.txt`.

Since transitive dependencies aren't pinned, it's possible that an update to a transitive dependency could cause a newly generated lambda layer to have different content event though it would be cached by the same `requirements.txt` hash.

Personally, I (Jesse) don't think this will be an issue. Consider the cases. Either an update in a transitive dependency can cause a problem, or cause no problems.
1. **An update to a transitive dependency causes a new problem.**  We will only notice the new problem if, locally, we remove, then rebuild our virtual environment. This kind of problem will only be visible in code running locally. This kind of problem won't show up in a deployment, unless we force the dependencies layer to be rebuilt. This kind of problem can be solved by pinning the version of the transitive dependency.
2. **An update to a transitive dependency causes no problems.** It's possible that the requirements installed in a fresh virtual environment will be different from those in a deployment, but in this case it isn't causing any issues.

If we ever need to force the dependencies lambda layer to be rebuild we can run `python scripts/stage_layer.py --force`.

**Comment by hannes-ucsc** [comment] 2020-04-29 00:35
We can't rely on the layer caching as a means to provide reproducibility. Being a cache, and not a primary build artefact, I should be able to delete it and still get a reproducible build. The important invariant we are pursuing (with some success) is: same source tree == same behaviour. Pinning all dependencies is a necessary prerequisite for that, independently of Lambda layer caching.

Imagine these two scenarios:

Scenario 1)

1) `prod` layer cache at hash 123, and hash of layer.zip is 234
1) `dev` layer cache at hash 123, and hash of layer.zip is 234
1) PR to `dev` is merged which updates `requirements.txt`
1) `dev` layer cache now 345, and hash of layer.zip is 456
1) a minor update to a transitive dependency is published
1) `dev` is promoted to `prod`, layer cache will be rebuilt due to change to requirements.txt
1) Update to transitive dependency is picked up 
1) `prod` layer cache now at 345, but hash of layer.zip is not 456 as in dev, but 567
1) `prod` breaks due to bug in transitive dependency

Scenario 2)

1) `prod` layer cache at hash 123, and hash of layer.zip is 234
1) `dev` layer cache at hash 123, and hash of layer.zip is 234
1) PR to `dev` is merged which does NOT update `requirements.txt`
1) `dev` layer cache still at 123, and hash of layer.zip is 234
1) a minor update to a transitive dependency is published
1) `dev` is promoted to `prod`, layer cache will not be be rebuilt since requirements.txt is the same
1) Update to transitive dependency is not picked up 
1) `prod` layer cache still at 123, hash of layer.zip is still 234 as in dev
1) `prod` doesn't break

The scenarios differ subtly and only incidentally, and there is very little indication as to what actually broke. Plus the breakage happens in prod, the worst possible case.

**Comment by melainalegaspi** [comment] 2020-04-29 18:54
@hannes-ucsc edit description

**Comment by hannes-ucsc** [comment] 2020-04-30 04:02
Create venv
Install the "install requirements" (wheel, setuptools et al)
pip freeze > 1.txt
Install requirements.txt
pip freeze > 2.txt
merge 2.txt minus 1.txt into requirements.txt
Install requirements.dev.txt
pip freeze > 3.txt
merge 3.txt - 2.txt - 1.txt into requirements.txt

All transitive requirements should be marked as such in a comment. Direct dependencies should come first, then comment, then transitive dependencies.

**Comment by hannes-ucsc** [comment] 2020-04-30 04:03
There are a bunch of direct dependencies that are currently not pinned. Those should be pinned, too.

**Comment by hannes-ucsc** [comment] 2020-04-30 04:19
Gitlab runs `pip list`. Be sure to monitor how these changes affect that listing. Ideally, the listing shouldn't change. The changes should be semantically neutral.

**Closed** 2020-06-16 22:27 UTC
Labels: debt, demoed, infra, orange
