### ISSUE TITLE
Set up integration tests

### ISSUE THREAD

**Issue by cricketsloan** [DataBiosphere/azul#70] opened 2018-07-13 23:25 UTC
We need to bring Orange into the integration test suite (DCP repo)

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/AZUL-76)
┆Project Name: azul
┆Issue Number: AZUL-76

**Comment by kozbo** [comment] 2018-08-06 22:56
Dupe of #75

**Closed by kozbo** 2018-08-06 22:56 UTC
