### ISSUE TITLE
Requesting delete of a duplicate matrix file from a dcp33 dataset 

### ISSUE THREAD

**Issue by bvizzier-ucsc** [DataBiosphere/azul#5761] opened 2023-12-06 21:01 UTC
[Slack thread](https://humancellatlas.slack.com/archives/C9XD6L0AD/p1701108889471639)

There is a duplicate matrix file in a dataset of dcp33 and the wrangling team is asking if we can remove it.

Project:  [95f07e6e-6a73-4e1b-a880-c83996b3aa5c](https://explore.data.humancellatlas.org/projects/95f07e6e-6a73-4e1b-a880-c83996b3aa5c/project-matrices)
File: GSE149689_matrix.mtx.gz

![image](https://github.com/DataBiosphere/azul/assets/15311001/0f8e276e-e887-477d-951d-6994badcffc6)

- [ ] Security design review completed; the Resolution of this issue does **not** …
  - [ ] … affect authentication; for example:
    - OAuth 2.0 with the application (API or Swagger UI)
    - Authentication of developers with Google Cloud APIs
    - Authentication of developers with AWS APIs
    - Authentication with a GitLab instance in the system
    - Password and 2FA authentication with GitHub
    - API access token authentication with GitHub
    - Authentication with 
  - [ ] … affect the permissions of internal users like access to
    - Cloud resources on AWS and GCP
    - GitLab repositories, projects and groups, administration
    - an EC2 instance via SSH
    - GitHub issues, pull requests, commits, commit statuses, wikis, repositories, organizations
  - [ ] … affect the permissions of external users like access to
    - TDR snapshots
  - [ ] … affect permissions of service or bot accounts
    - Cloud resources on AWS and GCP
  - [ ] … affect audit logging in the system, like
    - adding, removing or changing a log message that represents an auditable event
    - changing the routing of log messages through the system
  - [ ] … affect monitoring of the system
  - [ ] … introduce a new software dependency like
    - Python packages on PYPI
    - Command-line utilities
    - Docker images
    - Terraform providers
  - [ ] … add an interface that exposes sensitive or confidential data at the security boundary
  - [ ] … affect the encryption of data at rest
  - [ ] … require persistence of sensitive or confidential data that might require encryption at rest
  - [ ] … require unencrypted transmission of data within the security boundary
  - [ ] … affect the network security layer; for example by 
    - modifying, adding or removing firewall rules
    - modifying, adding or removing security groups
    - changing or adding a port a service, proxy or load balancer listens on
- [ ] Documentation on any unchecked boxes is provided in comments below

**Comment by hannes-ucsc** [comment] 2023-12-06 21:46
Duplicate of https://github.com/DataBiosphere/azul/issues/5701 which we closed because Azul does not have the ability to remove files from snapshots. Even in TDR, snapshots are immutable. So the only way to remove the file from Azul's index is to create a snapshot that does not contain it, and that's not something we can do.

**Closed as not planned** 2023-12-07 19:50 UTC
Labels: duplicate
