### ISSUE TITLE
Terra export of fastq files lists secondary bundles

### ISSUE THREAD

**Issue by danielsotirhos** [DataBiosphere/azul#1737] opened 2020-04-28 22:27 UTC
Follow-up to #916

[participants.tsv.zip](https://github.com/DataBiosphere/azul/files/4548894/participants.tsv.zip)

**Comment by melainalegaspi** [comment] 2020-04-29 18:52
@hannes-ucsc propose a solution

**Comment by hannes-ucsc** [comment] 2020-05-29 21:16
To explain what the issue is: when someone filters for fastq files and requests Terra handover,  they get a manifest that lists secondary bundles but doesn't list primary bundles. That is counter-intuitive and potentially harmful because the secondary bundles are always bigger (as they include all the files from the primary bundle).

We need to modify the logic implemented in the solution for #916. The current logic is to remove bundles that are a subset of other selected bundles. Always removing the superset bundles wouldn't work if the filter were `bam` OR `fastq` because they would remove the `bams` from the handover.

The logic should be to consider every file in the ES response and mark the smallest bundle containing that file. Then remove all unmarked bundles.

**Comment by hannes-ucsc** [comment] 2020-05-29 21:19
This is very complicated and I would rather post-pone this. Reimplementing the Terra Handover with Avro/PFB could be used to eliminate the bundle-centricity and make this issue obsolete.

**Comment by theathorn** [comment] 2020-06-09 21:26
Closing in favor of the Avro/PFB solution.

**Closed by theathorn** 2020-06-09 21:26 UTC
Labels: orange
