### ISSUE TITLE
Disease field is not indexed correctly in MARS dataset on prod

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#934] opened 2019-04-23 19:42 UTC
<img width="1095" alt="Screen Shot 2019-04-23 at 12 37 49 PM" src="https://user-images.githubusercontent.com/5143256/56610599-a784bb80-65c4-11e9-82a1-9fa05e123d21.png">

Known Diseases column is blank.

In metadata specimen_from_organism.disease is absent but `donor_organism.disease` is set to `"isolated hip osteoarthritis"`. The service response lists `specimens.disease` as `[]` which is displayed as blank.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-582)
┆Project Name: azul
┆Issue Number: AZUL-582

**Comment by hannes-ucsc** [comment] 2019-04-23 21:57
First reported by @NoopDog

**Comment by danielsotirhos** [comment] 2019-04-24 17:33
Closing ticket for intended behavior. For history of this issue see #527 and HumanCellAtlas/data-browser#335
Please note that this behavior will soon be changed when #707 (Samples tab) is completed and the process of accumulating property values into the SpecimenFromOrganism is no longer implemented.

**Closed** 2019-04-24 17:33 UTC
Labels: bug, code
