### ISSUE TITLE
make `requirement_update` is slow

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#2058] opened 2020-07-23 15:47 UTC
… because it needs to install the gevent package from source. Building gevent takes a long time.

The reason that we can't use the pre-built binary wheel seems to be that the build container uses an Alpine image.

https://pypi.org/project/gevent/

> Binary wheels cannot be installed on non-manylinux2010 compatible Linux systems, such as those that use `musl`, including Alpine Linux. Those systems must install from source.

`chalice package` when run on my machine doesn't seem to be affected, I guess because it doesn't run in a container there. It does run in a container on Gitlab. That container also uses the `build` image which is Alpine based.

**Comment by melainalegaspi** [comment] 2020-10-19 21:35
Duplicate of #2332

**Closed by melainalegaspi** 2020-10-19 21:35 UTC
Labels: debt, infra, orange
