### ISSUE TITLE
Results of `make format` run cause conflincts with `make pep8` command

### ISSUE THREAD

**Issue by achave11-ucsc** [DataBiosphere/azul#5195] opened 2023-05-09 21:10 UTC
… this was made visible in [Send GitLab host logs to CloudWatch (#3894) PR #5187](https://github.com/DataBiosphere/azul/pull/5187).

- [ ] Security design review completed; the Resolution of this issue does **not** …
  - [ ] … affect authentication; for example:
    - OAuth 2.0 with the application (API or Swagger UI)
    - Authentication of developers with Google Cloud APIs
    - Authentication of developers with AWS APIs
    - Authentication with a GitLab instance in the system
    - Password and 2FA authentication with GitHub
    - API access token authentication with GitHub
    - Authentication with 
  - [ ] … affect the permissions of internal users like access to
    - Cloud resources on AWS and GCP
    - GitLab repositories, projects and groups, administration
    - an EC2 instance via SSH
    - GitHub issues, pull requests, commits, commit statuses, wikis, repositories, organizations
  - [ ] … affect the permissions of external users like access to
    - TDR snapshots
  - [ ] … affect permissions of service or bot accounts
    - Cloud resources on AWS and GCP
  - [ ] … affect audit logging in the system, like
    - adding, removing or changing a log message that represents an auditable event
    - changing the routing of log messages through the system
  - [ ] … affect monitoring of the system
  - [ ] … introduce a new software dependency like
    - Python packages on PYPI
    - Command-line utilities
    - Docker images
    - Terraform providers
  - [ ] … add an interface that exposes sensitive or confidential data at the security boundary
  - [ ] … affect the encryption of data at rest
  - [ ] … require persistence of sensitive or confidential data that might require encryption at rest
  - [ ] … require unencrypted transmission of data within the security boundary
  - [ ] … affect the network security layer; for example by 
    - modifying, adding or removing firewall rules
    - modifying, adding or removing security groups
    - changing or adding a port a service, proxy or load balancer listens on
- [ ] Documentation on any unchecked boxes is provided in comments below

**Comment by achave11-ucsc** [comment] 2023-05-09 23:48
The failed GitHub test action produces the following diff after `make format` is ran…

```
index e805bed..07965db 100644
--- a/terraform/gitlab/gitlab.tf.json.template.py
+++ b/terraform/gitlab/gitlab.tf.json.template.py
@@ -1591,14 +1591,14 @@ emit_tf({} if config.terraform_component != 'gitlab' else {
                                                         "log_group_name": "/aws/cwagent/azul-gitlab",
                                                         "log_stream_name": f'/mnt/gitlab/logs/{path}.log'
                                                     } for path in [
-                                                        'gitaly/gitaly_ruby_json',
-                                                        'gitlab-shell/gitlab-shell',
-                                                        'nginx/gitlab_access',
-                                                        'nginx/gitlab_error',
-                                                        'nginx/gitlab_registry_access',
-                                                        'puma/puma_stderr',
-                                                        'puma/puma_stdout'
-                                                    ]
+                                                    'gitaly/gitaly_ruby_json',
+                                                    'gitlab-shell/gitlab-shell',
+                                                    'nginx/gitlab_access',
+                                                    'nginx/gitlab_error',
+                                                    'nginx/gitlab_registry_access',
+                                                    'puma/puma_stderr',
+                                                    'puma/puma_stdout'
+                                                ]
                                                 ),
                                                 *(
                                                     {
@@ -1606,20 +1606,20 @@ emit_tf({} if config.terraform_component != 'gitlab' else {
                                                         "log_group_name": "/aws/cwagent/azul-gitlab",
                                                         "log_stream_name": f'/mnt/gitlab/logs/gitlab-rails/{path}.log'
                                                     } for path in [
-                                                        'api_json',
-                                                        'application_json',
-                                                        'application',
-                                                        'audit_json',
-                                                        'auth',
-                                                        'database_load_balancing',
-                                                        'exceptions_json',
-                                                        'gitlab-shell',
-                                                        'graphql_json',
-                                                        'migrations',
-                                                        'production_json',
-                                                        'production',
-                                                        'sidekiq_client'
-                                                    ]
+                                                    'api_json',
+                                                    'application_json',
+                                                    'application',
+                                                    'audit_json',
+                                                    'auth',
+                                                    'database_load_balancing',
+                                                    'exceptions_json',
+                                                    'gitlab-shell',
+                                                    'graphql_json',
+                                                    'migrations',
+                                                    'production_json',
+                                                    'production',
+                                                    'sidekiq_client'
+                                                ]
                                                 ),
                                                 *(
                                                     {
@@ -1627,14 +1627,14 @@ emit_tf({} if config.terraform_component != 'gitlab' else {
                                                         "log_group_name": "/aws/cwagent/azul-gitlab",
                                                         "log_stream_name": f'/var/log/{path}'
                                                     } for path in [
-                                                        'amazon/ssm/amazon-ssm-agent.log',
-                                                        'audit/audit.log',
-                                                        'cloud-init.log',
-                                                        'cron',
-                                                        'maillog',
-                                                        'messages',
-                                                        'secure'
-                                                    ]
+                                                    'amazon/ssm/amazon-ssm-agent.log',
+                                                    'audit/audit.log',
+                                                    'cloud-init.log',
+                                                    'cron',
+                                                    'maillog',
+                                                    'messages',
+                                                    'secure'
+                                                ]
                                                 ),
                                             ]
                                         }
make: *** [Makefile:244: check_clean] Error 1
```

However, when implemented, the `make pep8` target fails locally with…
```
…/azul.sc/terraform/gitlab/gitlab.tf.json.template.py:1594:53: E122 continuation line missing indentation or outdented
…/azul.sc/terraform/gitlab/gitlab.tf.json.template.py:1595:53: E122 continuation line missing indentation or outdented
…/azul.sc/terraform/gitlab/gitlab.tf.json.template.py:1596:53: E122 continuation line missing indentation or outdented
…/azul.sc/terraform/gitlab/gitlab.tf.json.template.py:1597:53: E122 continuation line missing indentation or outdented
…/azul.sc/terraform/gitlab/gitlab.tf.json.template.py:1598:53: E122 continuation line missing indentation or outdented
…/azul.sc/terraform/gitlab/gitlab.tf.json.template.py:1599:53: E122 continuation line missing indentation or outdented
…/azul.sc/terraform/gitlab/gitlab.tf.json.template.py:1600:53: E122 continuation line missing indentation or outdented
…/azul.sc/terraform/gitlab/gitlab.tf.json.template.py:1601:49: E122 continuation line missing indentation or outdented
…/azul.sc/terraform/gitlab/gitlab.tf.json.template.py:1609:53: E122 continuation line missing indentation or outdented
…/azul.sc/terraform/gitlab/gitlab.tf.json.template.py:1610:53: E122 continuation line missing indentation or outdented
…/azul.sc/terraform/gitlab/gitlab.tf.json.template.py:1611:53: E122 continuation line missing indentation or outdented
…/azul.sc/terraform/gitlab/gitlab.tf.json.template.py:1612:53: E122 continuation line missing indentation or outdented
…/azul.sc/terraform/gitlab/gitlab.tf.json.template.py:1613:53: E122 continuation line missing indentation or outdented
…/azul.sc/terraform/gitlab/gitlab.tf.json.template.py:1614:53: E122 continuation line missing indentation or outdented
…/azul.sc/terraform/gitlab/gitlab.tf.json.template.py:1615:53: E122 continuation line missing indentation or outdented
…/azul.sc/terraform/gitlab/gitlab.tf.json.template.py:1616:53: E122 continuation line missing indentation or outdented
…/azul.sc/terraform/gitlab/gitlab.tf.json.template.py:1617:53: E122 continuation line missing indentation or outdented
…/azul.sc/terraform/gitlab/gitlab.tf.json.template.py:1618:53: E122 continuation line missing indentation or outdented
…/azul.sc/terraform/gitlab/gitlab.tf.json.template.py:1619:53: E122 continuation line missing indentation or outdented
…/azul.sc/terraform/gitlab/gitlab.tf.json.template.py:1620:53: E122 continuation line missing indentation or outdented
…/azul.sc/terraform/gitlab/gitlab.tf.json.template.py:1621:53: E122 continuation line missing indentation or outdented
…/azul.sc/terraform/gitlab/gitlab.tf.json.template.py:1622:49: E122 continuation line missing indentation or outdented
…/azul.sc/terraform/gitlab/gitlab.tf.json.template.py:1630:53: E122 continuation line missing indentation or outdented
…/azul.sc/terraform/gitlab/gitlab.tf.json.template.py:1631:53: E122 continuation line missing indentation or outdented
…/azul.sc/terraform/gitlab/gitlab.tf.json.template.py:1632:53: E122 continuation line missing indentation or outdented
…/azul.sc/terraform/gitlab/gitlab.tf.json.template.py:1633:53: E122 continuation line missing indentation or outdented
…/azul.sc/terraform/gitlab/gitlab.tf.json.template.py:1634:53: E122 continuation line missing indentation or outdented
…/azul.sc/terraform/gitlab/gitlab.tf.json.template.py:1635:53: E122 continuation line missing indentation or outdented
…/azul.sc/terraform/gitlab/gitlab.tf.json.template.py:1636:53: E122 continuation line missing indentation or outdented
…/azul.sc/terraform/gitlab/gitlab.tf.json.template.py:1637:49: E122 continuation line missing indentation or outdented
make: *** [pep8] Error 1
```

**Comment by dsotirho-ucsc** [comment] 2023-05-10 18:52
@nadove-ucsc: "The issue is arising due to the absence of a line break between the `for` keyword and the closing brace of the multiline dict literal that precedes it. Because the dict literal spans multiple lines."

**Comment by dsotirho-ucsc** [comment] 2023-05-10 18:54
@achave11-ucsc to confirm @nadove-ucsc's hypothesis.

**Comment by nadove-ucsc** [comment] 2023-05-11 03:34
[Hypothesis refuted, alternative proposed](https://github.com/DataBiosphere/azul/pull/5187#discussion_r1190593067)

**Comment by achave11-ucsc** [comment] 2023-05-11 18:18
[This suggestion](https://github.com/DataBiosphere/azul/pull/5187#discussion_r1191538370) seems ok with `format` and `pep8`.

**Comment by dsotirho-ucsc** [comment] 2023-05-11 18:54
@hannes-ucsc: "The alternative suggestion is acceptable. We don't have time to make it perfect."

**Closed as not planned by dsotirho-ucsc** 2023-05-11 18:54 UTC
Labels: wontfix, infra
