### ISSUE TITLE
Log forwarder timeout causes alarm

### ISSUE THREAD

**Issue by dsotirho-ucsc** [DataBiosphere/azul#5499] opened 2023-09-05 17:04 UTC
`forward_alb_logs` on `dev`:
```
[
    {
        "@timestamp": "2023-09-05 02:50:02.632",
        "@message": "START RequestId: 8c7a23b5-c005-4fe5-be49-d57ed09d3b05 Version: $LATEST\n"
    },
    {
        "@timestamp": "2023-09-05 02:50:33.669",
        "@message": "2023-09-05T02:50:33.669Z 8c7a23b5-c005-4fe5-be49-d57ed09d3b05 Task timed out after 31.04 seconds\n\n"
    },
    {
        "@timestamp": "2023-09-05 02:50:33.669",
        "@message": "END RequestId: 8c7a23b5-c005-4fe5-be49-d57ed09d3b05\n"
    },
    {
        "@timestamp": "2023-09-05 02:50:33.669",
        "@message": "REPORT RequestId: 8c7a23b5-c005-4fe5-be49-d57ed09d3b05\tDuration: 31036.93 ms\tBilled Duration: 31000 ms\tMemory Size: 128 MB\tMax Memory Used: 119 MB\t\n"
    }
]
```

`forward_s3_logs` on `anvilprod`:
```
[
    {
        "@timestamp": "2023-09-05 04:41:50.273",
        "@message": "START RequestId: c02c5df9-531c-417c-a15a-6c51b5a9f688 Version: $LATEST\n",
        "http_status": "",
        "error_code": ""
    },
    {
        "@timestamp": "2023-09-05 04:42:21.320",
        "@message": "2023-09-05T04:42:21.320Z c02c5df9-531c-417c-a15a-6c51b5a9f688 Task timed out after 31.05 seconds\n\n",
        "http_status": "",
        "error_code": ""
    },
    {
        "@timestamp": "2023-09-05 04:42:21.320",
        "@message": "END RequestId: c02c5df9-531c-417c-a15a-6c51b5a9f688\n",
        "http_status": "",
        "error_code": ""
    },
    {
        "@timestamp": "2023-09-05 04:42:21.320",
        "@message": "REPORT RequestId: c02c5df9-531c-417c-a15a-6c51b5a9f688\tDuration: 31047.86 ms\tBilled Duration: 31000 ms\tMemory Size: 128 MB\tMax Memory Used: 119 MB\t\n",
        "http_status": "",
        "error_code": ""
    }
]
```

----

- [ ] Security design review completed; the Resolution of this issue does **not** …
  - [ ] … affect authentication; for example:
    - OAuth 2.0 with the application (API or Swagger UI)
    - Authentication of developers with Google Cloud APIs
    - Authentication of developers with AWS APIs
    - Authentication with a GitLab instance in the system
    - Password and 2FA authentication with GitHub
    - API access token authentication with GitHub
    - Authentication with 
  - [ ] … affect the permissions of internal users like access to
    - Cloud resources on AWS and GCP
    - GitLab repositories, projects and groups, administration
    - an EC2 instance via SSH
    - GitHub issues, pull requests, commits, commit statuses, wikis, repositories, organizations
  - [ ] … affect the permissions of external users like access to
    - TDR snapshots
  - [ ] … affect permissions of service or bot accounts
    - Cloud resources on AWS and GCP
  - [ ] … affect audit logging in the system, like
    - adding, removing or changing a log message that represents an auditable event
    - changing the routing of log messages through the system
  - [ ] … affect monitoring of the system
  - [ ] … introduce a new software dependency like
    - Python packages on PYPI
    - Command-line utilities
    - Docker images
    - Terraform providers
  - [ ] … add an interface that exposes sensitive or confidential data at the security boundary
  - [ ] … affect the encryption of data at rest
  - [ ] … require persistence of sensitive or confidential data that might require encryption at rest
  - [ ] … require unencrypted transmission of data within the security boundary
  - [ ] … affect the network security layer; for example by 
    - modifying, adding or removing firewall rules
    - modifying, adding or removing security groups
    - changing or adding a port a service, proxy or load balancer listens on
- [ ] Documentation on any unchecked boxes is provided in comments below

**Comment by dsotirho-ucsc** [comment] 2023-09-05 20:39
@hannes-ucsc: "We've noticed two concurrent invocations. One succeeded, the other one timed out after 30 seconds. It is possible that it was still initializing the Python runtime when it timed out. Assignee to investigate further. Are we expecting to observe concurrent invocations? Does the INIT_START message precede or succeed the runtime initialization? We should log the object key passed to the lambda function. It would also be good to understand if the failed execution was retried or we basically dropped one log object."

**Comment by achave11-ucsc** [comment] 2023-11-07 18:47
This happened again, for `anvilprod`.


[CW Insights.](https://us-east-1.console.aws.amazon.com/cloudwatch/home?region=us-east-1#logsV2:logs-insights$3FqueryDetail$3D~(end~'2023-11-07T01*3a27*3a59.000Z~start~'2023-11-07T01*3a18*3a00.000Z~timeType~'ABSOLUTE~tz~'Local~editorString~'fields*20*40timestamp*2c*20*40message*2c*20*40logStream*2c*20*40log*0a*7c*20filter*20*40message*20like*20*2f8f96e00e*2f*0a*7c*20sort*20*40timestamp*20desc*0a*7c*20limit*2020~queryId~'1c96d8cce58b92ef-412c92c6-4291798-5fb524-f412fcfd1095644134bff15a~source~(~'*2faws*2flambda*2fazul-indexer-anvilprod-forward_alb_logs)))

**Comment by achave11-ucsc** [comment] 2023-12-01 20:22
Closing as dupe of https://github.com/DataBiosphere/azul/issues/5622.

**Closed as not planned** 2023-12-01 20:22 UTC
Labels: duplicate, spike:2
