### ISSUE TITLE
Projects endpoint times out with page size of 15

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/azul#414] opened 2018-10-12 19:53 UTC
https://service.staging.explore.data.humancellatlas.org/repository/projects?size=15&filters=%7B%7D
This times out.

`{"message": "Endpoint request timed out"}`

This passes (size =1)
https://service.staging.explore.data.humancellatlas.org/repository/projects?size=1&filters=%7B%7D

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/AZUL-270)
┆Project Name: azul
┆Issue Number: AZUL-270

**Comment by theathorn** [comment] 2018-10-17 17:56
Is this due to the data set with ~100K bundles?

**Comment by hannes-ucsc** [comment] 2018-10-19 05:57
Can't reproduce anymore. Probably fixed by #433.

**Closed by hannes-ucsc** 2018-10-19 05:57 UTC
Labels: CRITICAL, HCA, bug
