### ISSUE TITLE
Integration tests may fail intermittently

### ISSUE THREAD

**Issue by jessebrennan** [DataBiosphere/azul#1060] opened 2019-06-05 17:16 UTC
Not sure exactly what caused the first failure. Rerunning the tests allowed it to pass fine.

https://gitlab.dev.explore.data.humancellatlas.org/azul/azul/-/jobs/1934

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-660)
┆Project Name: azul
┆Issue Number: AZUL-660

**Comment by hannes-ucsc** [comment] 2019-10-17 03:45
Closing as dupe of #1174.

**Comment by jessebrennan** [comment] 2019-10-18 22:04
Looks like this is happening again 

https://gitlab.dev.explore.data.humancellatlas.org/azul/azul/-/jobs/4343

**Closed** 2020-02-25 00:21 UTC
Labels: bug, orange, test
