### ISSUE TITLE
Sell unused slot job is failing on dev Gitlab

### ISSUE THREAD

**Issue by jessebrennan** [DataBiosphere/azul#3153] opened 2021-06-16 22:13 UTC
Failing consistently since ~3pm yesterday (June 15)

![sell-failing.png](https://images.zenhubusercontent.com/5bfc77a68ffeb454062a138a/973eec72-96f0-4adb-a3e7-9dd89e67761b)

Here's the error

```
$ python3 scripts/sell_unused_slots.py
Traceback (most recent call last):
  File "scripts/sell_unused_slots.py", line 160, in <module>
    main(sys.argv[1:])
  File "scripts/sell_unused_slots.py", line 149, in main
    slot_manager = SlotManager(dry_run=args.dry_run)
  File "/builds/ucsc/azul/src/azul/bigquery_reservation.py", line 49, in __init__
    self.refresh()
  File "/builds/ucsc/azul/src/azul/bigquery_reservation.py", line 61, in refresh
    self.has_active_slots()
  File "/builds/ucsc/azul/src/azul/bigquery_reservation.py", line 92, in has_active_slots
    raise RequirementError('BigQuery slot commitment state is '
azul.RequirementError: ('BigQuery slot commitment state is inconsistent: some, but not all resources are missing', {None, 'projects/platform-hca-dev/locations/US/capacityCommitments/5862130503691966078'})
```

**Comment by theathorn** [comment] 2021-06-17 18:59
Spike to see if it's dup of #3013.

**Comment by noah-aviel-dove** [comment] 2021-06-23 07:49
#3013 Describes two different errors, this is a dupe of the second.

**Closed** 2021-06-23 18:52 UTC
Labels: bug, duplicate, infra, orange, spike:1
