### ISSUE TITLE
`KeyError: apiId` with `make local`

### ISSUE THREAD

**Issue by achave11** [DataBiosphere/azul#1641] opened 2020-03-17 19:04 UTC
Steps to reproduce:

1) Run the following command:
```
$ (cd lambdas/service/ && make local)
```

2) Make a GET request to `http://127.0.0.1:8000/`

3) The following is raised:
```
127.0.0.1 - - [17/Mar/2020 11:53:01] "GET / HTTP/1.1" 200 -
Received GET request to '/openapi' without parameters.
Caught exception for <function openapi at 0x10b0e1ea0>
Traceback (most recent call last):
  File "/Users/abrahamchavez/PycharmProjects/Azul/azul.sc/.venv/lib/python3.6/site-packages/chalice/app.py", line 1104, in _get_view_function_response
    response = view_function(**function_args)
  File "/Users/abrahamchavez/PycharmProjects/Azul/azul.sc/lambdas/service/app.py", line 203, in openapi
    gateway_id = app.current_request.context['apiId']
KeyError: 'apiId'
Returning 500 response with headers {"Content-Type": "text/plain"}. See next line for the first 1024 characters of the body.
Traceback (most recent call last):
  File "/Users/abrahamchavez/PycharmProjects/Azul/azul.sc/.venv/lib/python3.6/site-packages/chalice/app.py", line 1104, in _get_view_function_response
    response = view_function(**function_args)
  File "/Users/abrahamchavez/PycharmProjects/Azul/azul.sc/lambdas/service/app.py", line 203, in openapi
    gateway_id = app.current_request.context['apiId']
KeyError: 'apiId'
```

**Comment by jessebrennan** [comment] 2020-03-30 23:38
The easiest solution for this is just to wait until #1450 is resolved. Then this issue will go away naturally.

If we want to solve it immediately, we will need to get the API Gateway ID for the current deployment. There is code in `azul.deployment.aws` for this, but I was working under @hannes-ucsc's direction to remove this code, partly in #1626 and then completely in #556.

**Comment by hannes-ucsc** [comment] 2020-03-31 21:06
As long as only the `/` and `/openapi` routes are affected, I'm happy to wait for the resolution of #1450. Once you confirm this is the case, I will close this ticket in favour of #1450.

**Comment by jessebrennan** [comment] 2020-03-31 21:13
I just confirmed this is the case. Feel free to close 
![makelocal](https://user-images.githubusercontent.com/10734740/78075608-b558ca00-7359-11ea-9373-80ee60de5807.png)

**Comment by theathorn** [comment] 2020-04-09 18:51
@jessebrennan Make sure this doesn't affect the other routes.

**Comment by jessebrennan** [comment] 2020-04-13 17:30
I tested the repository and manifest endpoints Also. Everything seems to be working fine.

If there are any other endpoints specifically you'd like me to test, let me know.

**Comment by jessebrennan** [comment] 2020-04-16 17:26
It looks like this was reassigned to me, but I'm not sure why. I'm reassigning to Hannes to close / review.

**Comment by melainalegaspi** [comment] 2020-06-01 18:41
@hannes-ucsc : "Resolution looks good to me."

**Closed by melainalegaspi** 2020-06-01 18:41 UTC
Labels: bug, infra, orange
