### ISSUE TITLE
Compact manifest is empty and fails IT in anvildev

### ISSUE THREAD

**Issue by achave11-ucsc** [DataBiosphere/azul#4623] opened 2022-10-20 17:54 UTC
… for random seed set to `5325088861110752443`.
https://gitlab.anvil.gi.ucsc.edu/ucsc/azul/-/jobs/3400
```
======================================================================
FAIL: test_indexing (integration_test.IndexingIntegrationTest) [manifest] (catalog='anvil-it', format=None)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builds/ucsc/azul/test/integration_test.py", line 368, in subTest
    yield
  File "/builds/ucsc/azul/test/integration_test.py", line 549, in _test_manifest
    validator(catalog, response)
  File "/builds/ucsc/azul/test/integration_test.py", line 674, in _check_manifest
    self.__check_manifest(BytesIO(response), 'bundle_uuid')
  File "/builds/ucsc/azul/test/integration_test.py", line 750, in __check_manifest
    self.assertGreater(len(rows), 0)
AssertionError: 0 not greater than 0
======================================================================
FAIL: test_indexing (integration_test.IndexingIntegrationTest) [manifest] (catalog='anvil-it', format=<ManifestFormat.compact: 'compact'>)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builds/ucsc/azul/test/integration_test.py", line 368, in subTest
    yield
  File "/builds/ucsc/azul/test/integration_test.py", line 549, in _test_manifest
    validator(catalog, response)
  File "/builds/ucsc/azul/test/integration_test.py", line 674, in _check_manifest
    self.__check_manifest(BytesIO(response), 'bundle_uuid')
  File "/builds/ucsc/azul/test/integration_test.py", line 750, in __check_manifest
    self.assertGreater(len(rows), 0)
AssertionError: 0 not greater than 0
----------------------------------------------------------------------
Ran 13 tests in 356.771s
FAILED (failures=2, skipped=3)
make: *** [Makefile:167: integration_test] Error 1
Cleaning up project directory and file based variables 00:01
ERROR: Job failed: exit code 1
```

**Comment by melainalegaspi** [comment] 2022-10-20 18:53
@achave11 to determine if this is a duplicate of #4392

**Comment by danielsotirhos** [comment] 2022-10-24 18:50
@hannes-ucsc: "@noah-aviel-dove points out that all sources in `anvildev` are managed access, so this might not be a dup after all."

@noah-aviel-dove to attempt to reproduce and diagnose.

**Comment by danielsotirhos** [comment] 2022-10-24 21:52
Reoccurrence on anvil GitLab:
Seed: 3855468853845242342
Log: https://gitlab.anvil.gi.ucsc.edu/ucsc/azul/-/jobs/3639

IT job succeeded on 2nd attempt with a new random seed.

**Comment by noah-aviel-dove** [comment] 2022-10-25 00:48
This is due to the lack of discoverable files in the GTEx snapshot. The bundles were indexed normally and correctly; there simply weren't any files in the resulting index.

Similar to https://github.com/DataBiosphere/azul/issues/4392, the underlying cause is a single partition containing a greater number of bundles (66 in this case) than the minimum needed for the test (64), causing bundles from only source to be indexed. According to [this comment](https://github.com/DataBiosphere/azul/blob/018c8a4b2f2375f32ff1013e9f0af6ee1525c95e/test/integration_test.py#L269), the desired partition size for stable deployments is 512 (32 and 1024 are enforced as upper and lower bounds), so we would expect the tests to select only a single partition from a single source for indexing most of the time. Perhaps it would improve test durability if we shrank the partitions for the indexing test so that more sources are included?

Otherwise, nothing needs to be done to fix this since [the updated GTEx snapshot](https://github.com/DataBiosphere/azul/issues/4599) includes discoverable files.

**Comment by noah-aviel-dove** [comment] 2022-10-25 01:07
This applies to both the [first](https://github.com/DataBiosphere/azul/issues/4623#issue-1417032379) and [second](https://github.com/DataBiosphere/azul/issues/4623#issuecomment-1289664304) failures. The partition prefix is different but in both cases it is larger than 64 bundles.

**Comment by noah-aviel-dove** [comment] 2022-10-25 09:49
Correction: since we are still not indexing all files in the AnVIL snapshots, it may still be hypothetically possible to index a partition that includes no files.

**Comment by theathorn** [comment] 2022-10-25 18:38
@hannes-ucsc to review spike results.

**Comment by hannes-ucsc** [comment] 2022-10-31 17:26
I'd like to sit on this and see how prevalent it is, now that the GTEx issue has been fixed.

**Comment by hannes-ucsc** [comment] 2024-04-15 18:08
No further occurrences.

**Closed** 2024-04-15 18:29 UTC
Labels: bug, wontfix, test, orange
