### ISSUE TITLE
Stall occured when running integration tests in sandbox

### ISSUE THREAD

**Issue by jessebrennan** [DataBiosphere/azul#2834] opened 2021-02-24 18:39 UTC
Here's the build log https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/10584

From ~ 17:55:26 to 17:59:55 a stall is apparent.

**Comment by melainalegaspi** [comment] 2021-02-24 20:03
Duplicate of #1618

**Closed** 2021-02-24 20:03 UTC
Labels: duplicate, orange
