### ISSUE TITLE
Support for Terra/Azure - Phase 1

### ISSUE THREAD

**Issue by bvizzier-ucsc** [DataBiosphere/azul#5952] opened 2024-02-12 19:22 UTC
Terra is implementing support for Microsoft Azure, and this will become the Anvil's primary data and analysis platform later this year.

There have been several discussions about this and the Phase 1 plans are for the Data Explorer to:
1) Index the data hosted in Azure by importing the Azure Synapse Parquet files into Big Query and then using Big Query to be used to explore data that is hosted on both Azure and GCP.
2) Hand-off the references to the user selected data to Terra/Azure for analysis. 

A second, later phase will involve using Synapse directly to process the data on Azure. 

[Preliminary information provided by the Broad.](https://docs.google.com/document/d/1DTWHVfk97IALpyFQ2bPCovcI_6RNbelEx3gxnkJv6bI/edit?usp=sharing)

For AnVIL, a small subset of the data will continue to be co-hosted on GCP in addition to Azure.  This is relevant since people wanting to do analysis on a specific platform may have ingress and egress charges.

**Comment by bvizzier-ucsc** [comment] 2024-04-29 16:49
Recommend closing this ticket as a duplicate of https://github.com/DataBiosphere/azul/issues/5610 and promoting that ticket to an epic.

**Comment by dsotirho-ucsc** [comment] 2024-04-29 18:45
Closing as duplicate of #5610

**Closed as not planned** 2024-04-29 18:45 UTC
Labels: duplicate
