### ISSUE TITLE
Setup CloudWatch alarm for ClamAV notifications 

### ISSUE THREAD

**Issue by amarjandu** [DataBiosphere/azul#3895] opened 2022-02-24 22:32 UTC
The `clamav` and `freshclam` containers emit a distinctive log message indicating success or failure of the process running in the container, based on its exit status. Both messages should ultimately end up as notifications in the monitoring Slack channel.

**Comment by dsotirho-ucsc** [comment] 2023-06-27 21:05
@hannes-ucsc: "Spike to identify the log message that indicates ClamAV success and failure."

**Comment by achave11-ucsc** [comment] 2023-06-28 18:27
**CloudWatch Logs Insights**  
region: us-east-1  
log-group-names: /aws/cwagent/azul-gitlab 
log-stream-names: /var/log/messages
start-time: 2023-06-25T13:45:02.244Z  
end-time: 2023-06-25T15:33:57.905Z  
query-string:
```
fields @timestamp, @message, @logStream, @log
| filter @logStream = "/var/log/messages"
| filter @message like 'docker: clamscan'
| sort @timestamp desc
| limit 20
```
```
[
    {
        "@timestamp": "2023-06-25 14:30:51.462",
        "@message": "Jun 25 14:30:51 ip-172-71-0-215 docker: clamscan succeeded",
        "@logStream": "/var/log/messages",
        "@log": "122796619775:/aws/cwagent/azul-gitlab"
    }
]
```
… alternatively, on a failure the message [should be similar](https://github.com/DataBiosphere/azul/blob/develop/terraform/gitlab/gitlab.tf.json.template.py#L1523) but ending in the post-fix `… clamscan failed`.
This log message is also expected to happen weekly on Saturdays. Additionally, the freshclam failed/success scan can also be [found by looking](https://github.com/DataBiosphere/azul/blob/develop/terraform/gitlab/gitlab.tf.json.template.py#L1510) for the post -fix `freshclam succeeded`.

**Comment by achave11-ucsc** [comment] 2023-06-28 18:46
@hannes-ucsc: "Spike again to determine if it is possible to trigger an cloudwatch metric alarm when the age of the most recent message matching a particular substring exceeds a given threshold. We could use this to look for `docker: clamscan` and raise an alarm if the most recent match dates back more than a week."

**Comment by dsotirho-ucsc** [comment] 2023-06-29 00:22
> …determine if it is possible to trigger an cloudwatch metric alarm when the age of the most recent message matching a particular substring exceeds a given threshold.

This is possible using a metric filter for the matching string, and metric alarm using the metric filter finds less than a threshold of `1` over a given period. The patch below shows how this can be done. 

<details>
<summary>Expand to see patch</summary>

Note: This patch adds the alarm to `cloudwatch.tf.json.template.py` for testing, however if implemented we'd want to add this to `shared.tf.json.template.py`

```
Index: terraform/cloudwatch.tf.json.template.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/terraform/cloudwatch.tf.json.template.py b/terraform/cloudwatch.tf.json.template.py
--- a/terraform/cloudwatch.tf.json.template.py	(revision ec2a7ee44916d5dac5f521a01a27bbec0abeb4e5)
+++ b/terraform/cloudwatch.tf.json.template.py	(date 1688055681816)
@@ -173,6 +173,54 @@
                     }
                     for lambda_ in config.lambda_names()
                 ),
+                {
+                    'aws_cloudwatch_log_metric_filter': {
+                        'clamscan': {
+                            'name': config.qualified_resource_name('clamscan', suffix='.filter'),
+                            # Patterns that include non-alphanumeric characters must be
+                            # wrapped in double quotation marks ("")
+                            'pattern': '"docker: clamscan"',
+                            'log_group_name': '/aws/cwagent/azul-gitlab',
+                            'metric_transformation': {
+                                'name': config.qualified_resource_name('clamscan'),
+                                'namespace': 'LogMetrics',
+                                'value': 1,
+                                'default_value': 0,
+                            }
+                        }
+                    }
+                },
+                {
+                    'aws_cloudwatch_metric_alarm': {
+                        'clamscan': {
+                            'alarm_name': config.qualified_resource_name('clamscan', suffix='.alarm'),
+                            'comparison_operator': 'LessThanThreshold',
+                            'threshold': 1,
+                            'datapoints_to_alarm': 1,
+                            'evaluation_periods': 1,
+                            'treat_missing_data': 'breaching',
+                            'alarm_actions': ['${data.aws_sns_topic.monitoring.arn}'],
+                            'ok_actions': ['${data.aws_sns_topic.monitoring.arn}'],
+                            # Using a metric query to fill in missing datapoints with a value of zero
+                            'metric_query': [
+                                {
+                                    'id': 'log_count_filled',
+                                    'expression': 'FILL(log_count_raw, 0)',
+                                    'return_data': True,
+                                },
+                                {
+                                    'id': 'log_count_raw',
+                                    'metric': {
+                                        'metric_name': config.qualified_resource_name('clamscan'),
+                                        'namespace': 'LogMetrics',
+                                        'period': 7 * 24 * 60 * 60,
+                                        'stat': 'Sum',
+                                    }
+                                }
+                            ]
+                        }
+                    }
+                }
             )
             if config.enable_monitoring else
             ()

```

</details>

> We could use this to look for `docker: clamscan` and raise an alarm if the most recent match dates back more than a week.

This will not work due to a maximum allowed evaluation period of 1 day. Testing with a 7 day evaluation period I got the error:

```
│ Error: creating CloudWatch Metric Alarm (azul-clamscan-daniel.alarm): ValidationError: Metrics cannot be checked across more than a day (EvaluationPeriods * Period must be <= 86400)
│ 	status code: 400, request id: 8f46fc7c-3000-4c85-99df-35ab1343fe4d
│
│   with aws_cloudwatch_metric_alarm.clamscan,
│   on cloudwatch.tf.json line 285, in resource[7].aws_cloudwatch_metric_alarm[0].clamscan:
│  285:                     }
```

https://docs.aws.amazon.com/AmazonCloudWatch/latest/APIReference/API_PutMetricAlarm.html
> An alarm's total current evaluation period can be no longer than one day, so Period multiplied by EvaluationPeriods cannot be more than 86,400 seconds.

**Comment by hannes-ucsc** [comment] 2023-06-29 03:42
Please inline the patch in the comment instead of attaching it.

**Comment by achave11-ucsc** [comment] 2023-06-29 18:52
Continue spike to determine how long a `clamscan` run including `freshclam` takes on `dev`.
Lower bound as well, youngest instance is `anvilprod`.

**Comment by dsotirho-ucsc** [comment] 2023-06-29 23:56
Average time taken for clamscan to complete:

| Avg Time | Instance |
|---|---|
| 6:19:37 | HCA dev |
| 4:26:42 | HCA prod |
| 3:46:02 | AnVIL dev |
| 5:35:23 | AnVIL prod |

<details>
<summary> Expand for full list of logs evaluated</summary>

| Time Taken | Logs |
|---|---|
|  | HCA dev |
| 6:16:35 | Jun  4 08:00:35 ip-172-71-0-215 docker: freshclam succeeded<br>Jun  4 14:17:10 ip-172-71-0-215 docker: clamscan succeeded |
| 6:12:17 | Jun 11 08:00:28 ip-172-71-0-215 docker: freshclam succeeded<br>Jun 11 14:12:45 ip-172-71-0-215 docker: clamscan succeeded |
| 6:19:12 | Jun 18 08:00:28 ip-172-71-0-215 docker: freshclam succeeded<br>Jun 18 14:19:40 ip-172-71-0-215 docker: clamscan succeeded |
| 6:30:23 | Jun 25 08:00:28 ip-172-71-0-215 docker: freshclam succeeded<br>Jun 25 14:30:51 ip-172-71-0-215 docker: clamscan succeeded |
|  |  |
|  | HCA prod |
| 4:24:02 | Jun 11 08:00:27 ip-172-72-0-59 docker: freshclam succeeded<br>Jun 11 12:24:29 ip-172-72-0-59 docker: clamscan succeeded |
| 4:26:07 | Jun 18 08:00:26 ip-172-72-0-59 docker: freshclam succeeded<br>Jun 18 12:26:33 ip-172-72-0-59 docker: clamscan succeeded |
| 4:29:58 | Jun 25 08:00:29 ip-172-72-0-59 docker: freshclam succeeded<br>Jun 25 12:30:27 ip-172-72-0-59 docker: clamscan succeeded |
|  |  |
|  | AnVIL dev |
| 3:29:03 | Jun  4 08:00:22 ip-172-73-0-46 docker: freshclam succeeded<br>Jun  4 11:29:25 ip-172-73-0-46 docker: clamscan succeeded |
| 3:34:55 | Jun 11 08:00:41 ip-172-73-0-46 docker: freshclam succeeded<br>Jun 11 11:35:22 ip-172-73-0-46 docker: clamscan succeeded |
| 4:02:07 | Jun 18 08:00:27 ip-172-73-0-46 docker: freshclam succeeded<br>Jun 18 12:02:34 ip-172-73-0-46 docker: clamscan succeeded |
| 3:58:04 | Jun 25 08:00:31 ip-172-73-0-46 docker: freshclam succeeded<br>Jun 25 11:58:35 ip-172-73-0-46 docker: clamscan succeeded |
|  |  |
|  | AnVIL prod |
| 5:29:17 | Jun 11 08:00:27 ip-172-74-0-28 docker: freshclam succeeded<br>Jun 11 13:29:44 ip-172-74-0-28 docker: clamscan succeeded |
| 5:43:54 | Jun 18 08:00:28 ip-172-74-0-28 docker: freshclam succeeded<br>Jun 18 13:44:22 ip-172-74-0-28 docker: clamscan succeeded |
| 5:32:57 | Jun 25 08:00:29 ip-172-74-0-28 docker: freshclam succeeded<br>Jun 25 13:33:26 ip-172-74-0-28 docker: clamscan succeeded |
|  |  |

</details>

**Comment by achave11-ucsc** [comment] 2023-06-30 19:08
@hannes-ucsc: "Change schedule to running it twice a day at 1am and 1pm. Will set the evaluation period to 18 hours (8h upper bound on running time - 2h lower bound on running time + 12h period)."

**Comment by hannes-ucsc** [comment] 2024-02-23 00:53
The service units on the GL instance emit four log messages:

1) `freshclam succeeded`
2) `freshclam failed`
3) `clamscan succeeded`
4) `clamscan failed`

There should be an immediate alarm when 2 or 4 is logged. There should be an alarm if neither 1 or 2 is logged within an 18h period. There should be an alarm if neither 3 or 4 is logged within an 18h period.

**Comment by hannes-ucsc** [comment] 2024-03-01 00:59
For demo, place EICAR test file on the `dev` instance of GitLab, disable the `freshclam` SystemD unit on the `anvildev` instance and disable the `clamscan` SystemD unit on the `anvilprod` instance. Perform these steps just in time so that we can observe the resulting alarms on the day of the demo. Remove author's public key from GitLab anvilprod instance.

**Comment by dsotirho-ucsc** [comment] 2024-07-16 21:21
@hannes-ucsc: "I'd like to wait demoing this until the false alarms are addressed by #6114."

**Comment by dsotirho-ucsc** [comment] 2024-08-13 21:04
Removing `demo blocked` label now that #6114 has been merged.

**Comment by dsotirho-ucsc** [comment] 2024-08-27 21:30
@hannes-ucsc: "@dsotirho-ucsc to reset `gitlab.anvildev` and `gitlab.anvilprod`. We will wait until standup tomorrow morning to ensure that all alarms are back to green and that the author's public key was removed from the GitLab instance. Lastly, re-assign @dsotirho-ucsc, move issue back to Stable and close."

**Comment by dsotirho-ucsc** [comment] 2024-08-28 18:52
Removal of the SSH key has been confirmed. The clamscan alarm is still `In alarm` on `dev`, cleared on both `anvildev` and `anvilprod`.

**Closed** 2024-08-29 18:43 UTC
Labels: enh, demoed, compliance, orange, spike:1, spike:3, spike:5, demo, gitlab, -
