### ISSUE TITLE
Organism age unit in response is null for some hits 

### ISSUE THREAD

**Issue by melainalegaspi** [DataBiosphere/azul#2634] opened 2020-12-16 19:42 UTC
See description of #2621.

![image](https://user-images.githubusercontent.com/5143256/102646899-b0bb8800-4119-11eb-9b51-222f83c62e8d.png)

Those `null` units shouldn't be there if the indexed metadata specifies a unit. If it doesn't this ticket is either invalid or we need to check if the schema specifies a default unit in which case we should use that instead of `None`.

**Comment by melainalegaspi** [comment] 2020-12-16 19:43
@hannes-ucsc fill in description

**Comment by hannes-ucsc** [comment] 2020-12-18 18:17
Description filled in. Spike to validate and specify solution.

**Comment by danielsotirhos** [comment] 2020-12-19 00:01
Consider the case where a bundle has a `donor_organism` document that doesn't have an `organism_age` nor `organism_age_unit` field. These fields are not required by the `donor_organism` [schema](https://schema.humancellatlas.org/type/biomaterial/13.0.0/donor_organism) and if absent each will be given the value `None` by the [metadata-api](https://github.com/DataBiosphere/hca-metadata-api/blob/effd20ccac94f1dac82fe6c453880c637a0d7547/src/humancellatlas/data/metadata/api.py#L271) and likewise `None` will be assigned to the [inner entity fields](https://github.com/DataBiosphere/azul/blob/03fbcca5be4972af381f461cb2a5461f12edde2f/src/azul/plugins/metadata/hca/transform.py#L523) `contents.donors.organism_age_value` and `contents.donors.organism_age_units`. Because these are the [fields attached to the facets](https://github.com/DataBiosphere/azul/blob/03fbcca5be4972af381f461cb2a5461f12edde2f/src/azul/plugins/metadata/hca/__init__.py#L169) `organismAgeValue` and `organismAgeUniit`, `None` will end up as a value in each.

**Comment by achave11** [comment] 2021-01-13 19:15
As @danielsotirhos mentioned, [donor_organism schema](https://schema.humancellatlas.org/type/biomaterial/15.5.0/donor_organism) does not require `organism_age` (i.e. `organism_age_value`) and `organism_age_unit`. It is worth noting that `organism_age_unit` is of `object` type with a specific [time unit ontology](https://schema.humancellatlas.org/module/ontology/5.3.5/time_unit_ontology). If provided, it only requires the `text` field which describes "The name of a time unit being used."
There are no recommendations for a default `unit` value.

**Comment by achave11** [comment] 2021-01-14 18:44
The metadata for `links_id=a57bdaf1-8541-4cbe-90b0-e8e2d5ae6b32` & `version=2019-09-06T19:26:08.074412Z` contain the following `for donor_organism_0.json`…
```
"donor_organism_0.json": {
        "describedBy": "https://schema.humancellatlas.org/type/biomaterial/15.4.0/donor_organism",
        "schema_type": "biomaterial",
        "biomaterial_core": {…},
        "human_specific": {…},
        "genus_species": […],
        "sex": "male",
        "is_living": "yes",
        "organism_age": "62",
        "development_stage": […],
        "diseases": […],
        "medical_history": {…},
        "provenance": {…}
    }
```
…as can be observed, the metadata for `donor_organism` does not specify a `organism_age_unit` and therefore, when it is indexed, it gets minted as `null`.

**Comment by hannes-ucsc** [comment] 2021-01-14 19:29
That subgraph does not exist in the most recent snapshot, the one that `dev` is currently set to:

![image](https://user-images.githubusercontent.com/5143256/104638985-b98d7400-565b-11eb-911d-d697aa022bd5.png)

Where did you get this from?

**Comment by achave11** [comment] 2021-01-14 20:09
>Where did you get this from?

I believe the snapshot is `hca_dev_20201203___20201210`.

**Comment by hannes-ucsc** [comment] 2021-01-14 21:41
Ok, confirmed.

![image](https://user-images.githubusercontent.com/5143256/104652505-12660800-566e-11eb-8170-fa07ad2167e1.png)

**Comment by hannes-ucsc** [comment] 2021-01-14 21:42
I'm sure that's a metadata omission. It's pretty obvious from the other properties that the donor age is in years.

**Closed** 2021-01-14 21:42 UTC
Labels: bug, code, invalid, orange, spike:1
