### ISSUE TITLE
Time-boxed TDR requests should not be retried

### ISSUE THREAD

**Issue by danielsotirhos** [DataBiosphere/azul#4067] opened 2022-04-07 20:24 UTC
`[WARNING] 2022-04-06T22:56:01.847Z a5f4bfdf-78a2-4589-8ab4-49bea514160e Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='data.terra.bio', port=443): Read timed out. (read timeout=20.0)")': /api/repository/v1/snapshots?offset=0&limit=200&sort=created_date&direction=asc`

Note the timeout is 20 not 5 because of https://github.com/DataBiosphere/azul/issues/4066 . Independently of that there should not be any retries. Currently there seems to be 2.

**Comment by noah-aviel-dove** [comment] 2022-04-07 21:16
I think this is a dupe of https://github.com/DataBiosphere/azul/issues/4053 based on my spike results

**Comment by hannes-ucsc** [comment] 2022-04-07 22:42
https://github.com/DataBiosphere/azul/issues/4053#issuecomment-1092275572

**Comment by hannes-ucsc** [comment] 2022-04-12 17:26
For demo, show absence of the log message (see description) from CloudWatch logs in `prod` two weeks after the fix lands in `prod`.

**Closed** 2022-05-31 21:09 UTC
Labels: bug, demoed, orange, demo, service
