### ISSUE TITLE
`projectTitle` alternates between array and string in /projects endpoint

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/azul#413] opened 2018-10-12 17:42 UTC
Can projectTitle just be a string?

Instead we are seeing either a string or array:

![image.png](https://images.zenhubusercontent.com/57323611bf93871ccd9ad094/98835071-3a60-428e-abe0-532cd16fca73)

![image.png](https://images.zenhubusercontent.com/57323611bf93871ccd9ad094/55116845-248e-469f-a45c-eb7debdf71e4)

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/AZUL-269)
┆Project Name: azul
┆Issue Number: AZUL-269

**Comment by Ben-Wu** [comment] 2018-10-22 19:00
I can't reproduce this on any of the 76 projects currently on dev.  They all have strings as titles including the one in the screenshot that has an array.

I tested it in this notebook here but github doesn't seem to want to render it:
https://gist.github.com/Ben-Wu/c0bc73572e400c06fe160c4cd9bd8728

@NoopDog Can you double check if this is still valid?

**Comment by theathorn** [comment] 2018-10-25 18:21
@frano-m Does this still happen?

**Comment by hannes-ucsc** [comment] 2018-11-02 17:37
Closing. I can't reproduce this either and that's not surprising because this ticket dates from before we added indexer aggregation.

**Closed by hannes-ucsc** 2018-11-02 17:37 UTC
Labels: bug, hca
