### ISSUE TITLE
Handling of `deploy:runner` is ambiguous

### ISSUE THREAD

**Issue by achave11-ucsc** [DataBiosphere/azul#6403] opened 2024-07-12 18:52 UTC
- [ ] Digest could change without the tag changing
- [ ] Developers may confuse the runner a.k.a executor image with the gitlab-runner image

**Comment by achave11-ucsc** [comment] 2024-07-12 19:18
Assignee to consider next steps.

**Comment by hannes-ucsc** [comment] 2024-09-04 19:47
Duplicate of #6520

**Closed as not planned** 2024-09-04 19:47 UTC
Labels: duplicate
