### ISSUE TITLE
High request rate causes occasional failure `test_concurrent_portal_db_crud`

### ISSUE THREAD

**Issue by jessebrennan** [DataBiosphere/azul#2845] opened 2021-03-02 01:28 UTC
```
ERROR: test_concurrent_portal_db_crud (integration_test.PortalRegistrationIntegrationTest)
Use multithreading to simulate multiple users simultaneously modifying
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builds/ucsc/azul/test/azul_test_case.py", line 125, in wrapped
    return method(*args, **kwargs)
  File "/builds/ucsc/azul/test/integration_test.py", line 730, in test_concurrent_portal_db_crud
    self.assertTrue(all(f.result() is None for f in futures))
  File "/builds/ucsc/azul/test/integration_test.py", line 730, in <genexpr>
    self.assertTrue(all(f.result() is None for f in futures))
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/builds/ucsc/azul/test/integration_test.py", line 725, in run
    self.portal_service._crud(lambda db: [*db, mock_entry])
  File "/builds/ucsc/azul/src/azul/portal_service.py", line 172, in _crud
    self._write_db(db, version)
  File "/builds/ucsc/azul/src/azul/portal_service.py", line 214, in _write_db
    response = self.client.put_object(Bucket=self.bucket,
  File "/build/.venv/lib/python3.8/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/build/.venv/lib/python3.8/site-packages/botocore/client.py", line 661, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (SlowDown) when calling the PutObject operation (reached max retries: 4): Please reduce your request rate.
```

https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/11158

**Comment by jessebrennan** [comment] 2021-03-02 01:31
This is probably just relevant to #2831 which revealed this error in the sandbox, so I decided close this ticket and refer the problem to @noah-aviel-dove.

**Comment by hannes-ucsc** [comment] 2021-03-02 18:28
Triage as potential duplicate of #2399 and #2400.

**Comment by melainalegaspi** [comment] 2021-03-02 19:48
Confirmed duplicate of #2399.

**Closed by melainalegaspi** 2021-03-02 19:48 UTC
Labels: debt, duplicate, orange, test
