### ISSUE TITLE
Research most recent index failures

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#1693] opened 2020-04-09 16:42 UTC
Five messages in total:

[azul-fail-dev.zip](https://github.com/DataBiosphere/azul/files/4457513/azul-fail-dev.zip)

**Comment by danielsotirhos** [comment] 2020-04-09 19:41
@hannes-ucsc The fails appear to be caused by #1678 which is currently in QA

I was able to match given errors by bundle uuid to the full error messages in azul-indexer-dev-index and all were due to the same issue trying to sort the `organ_part` list when it containied both `str` and `None` type values

```
[WARNING]	2020-04-09T07:33:17.401Z	ee7d2cd9-ee02-5a8d-b5bb-7bd13fe277de	Worker failed to handle message {'action': 'add', 'notification': {'query': {'query': {'bool': {'must_not': [{'term': {'admin_deleted': True}}], 'must': [{'exists': {'field': 'files.project_json'}}, {'prefix': {'uuid': '52'}}]}}}, 'subscription_id': 'cafebabe-feed-4bad-dead-beaf8badf00d', 'transaction_id': 'd53364fb-e233-4beb-8d34-dc4992c8eb8e', 'match': {'bundle_uuid': '52245757-73ba-43a2-a78d-0eba01cb4ce1', 'bundle_version': '2019-09-26T022557.424404Z'}}}.
Traceback (most recent call last):
  File "/var/task/app.py", line 202, in index
    contributions = indexer.transform(notification, delete=False)
  File "/var/task/azul/indexer/__init__.py", line 151, in transform
    metadata_files=metadata_files))
  File "/var/task/azul/project/hca/transformers.py", line 586, in transform
    cell_suspensions=list(map(self._cell_suspension, visitor.cell_suspensions.values())),
  File "/var/task/azul/project/hca/transformers.py", line 259, in _cell_suspension
    'organ_part': sorted(organ_parts)
TypeError: '<' not supported between instances of 'str' and 'NoneType'
```

```
[WARNING]	2020-04-09T07:33:54.161Z	10a0717c-3366-593f-9843-2674e1632244	Worker failed to handle message {'action': 'add', 'notification': {'query': {'query': {'bool': {'must_not': [{'term': {'admin_deleted': True}}], 'must': [{'exists': {'field': 'files.project_json'}}, {'prefix': {'uuid': 'cb'}}]}}}, 'subscription_id': 'cafebabe-feed-4bad-dead-beaf8badf00d', 'transaction_id': '804f7ca6-e339-4dba-8e9e-e91f68f16cfe', 'match': {'bundle_uuid': 'cb88115c-75ef-4e8e-bbd7-a48e18960344', 'bundle_version': '2019-09-26T034726.748575Z'}}}.
Traceback (most recent call last):
  File "/var/task/app.py", line 202, in index
    contributions = indexer.transform(notification, delete=False)
  File "/var/task/azul/indexer/__init__.py", line 151, in transform
    metadata_files=metadata_files))
  File "/var/task/azul/project/hca/transformers.py", line 586, in transform
    cell_suspensions=list(map(self._cell_suspension, visitor.cell_suspensions.values())),
  File "/var/task/azul/project/hca/transformers.py", line 259, in _cell_suspension
    'organ_part': sorted(organ_parts)
TypeError: '<' not supported between instances of 'str' and 'NoneType'
```

```
[WARNING]	2020-04-09T07:33:48.41Z	f4429afd-8f4f-5207-a656-cdf55d5f507a	Worker failed to handle message {'action': 'add', 'notification': {'query': {'query': {'bool': {'must_not': [{'term': {'admin_deleted': True}}], 'must': [{'exists': {'field': 'files.project_json'}}, {'prefix': {'uuid': 'cb'}}]}}}, 'subscription_id': 'cafebabe-feed-4bad-dead-beaf8badf00d', 'transaction_id': 'db756f72-756c-4d51-92ae-c55b661cf38b', 'match': {'bundle_uuid': 'cb97a8e3-8593-45df-bc63-caaa9200d3c4', 'bundle_version': '2019-09-24T093431.333569Z'}}}.
Traceback (most recent call last):
  File "/var/task/app.py", line 202, in index
    contributions = indexer.transform(notification, delete=False)
  File "/var/task/azul/indexer/__init__.py", line 151, in transform
    metadata_files=metadata_files))
  File "/var/task/azul/project/hca/transformers.py", line 586, in transform
    cell_suspensions=list(map(self._cell_suspension, visitor.cell_suspensions.values())),
  File "/var/task/azul/project/hca/transformers.py", line 259, in _cell_suspension
    'organ_part': sorted(organ_parts)
TypeError: '<' not supported between instances of 'NoneType' and 'str'
```

```
[WARNING]	2020-04-09T07:33:00.301Z	498cdcb6-c820-5545-a86b-8bbe19c8de3e	Worker failed to handle message {'action': 'add', 'notification': {'query': {'query': {'bool': {'must_not': [{'term': {'admin_deleted': True}}], 'must': [{'exists': {'field': 'files.project_json'}}, {'prefix': {'uuid': '1b'}}]}}}, 'subscription_id': 'cafebabe-feed-4bad-dead-beaf8badf00d', 'transaction_id': '33fdecf9-d4f5-4c04-9a25-797895791a55', 'match': {'bundle_uuid': '1b6d8348-d6e9-406a-aa6a-7ee886e52bf9', 'bundle_version': '2019-09-24T093431.335263Z'}}}.
Traceback (most recent call last):
  File "/var/task/app.py", line 202, in index
    contributions = indexer.transform(notification, delete=False)
  File "/var/task/azul/indexer/__init__.py", line 151, in transform
    metadata_files=metadata_files))
  File "/var/task/azul/project/hca/transformers.py", line 586, in transform
    cell_suspensions=list(map(self._cell_suspension, visitor.cell_suspensions.values())),
  File "/var/task/azul/project/hca/transformers.py", line 259, in _cell_suspension
    'organ_part': sorted(organ_parts)
TypeError: '<' not supported between instances of 'NoneType' and 'str'
```

**Comment by danielsotirhos** [comment] 2020-04-09 23:21
Assigned to @hannes-ucsc for closing as duplicate?

**Comment by danielsotirhos** [comment] 2020-04-10 22:33
For the fail detailed in `azul-fail-dev.fifo.json` I was able to track down a timeout that occurred after 300 seconds while 99,788 contributions were bing aggregated, however I haven't been able to find any further details the cause of the timeout.

Details from fail queue relevant to the search:
```
"SenderId": "AROARZFZ7W77VNWF46R45:azul-indexer-dev-write",
"entity_type": "projects",
"entity_id": "e0009214-c0a0-4a7b-96e2-d6a83e966ce0",        # Tabula Muris
"SentTimestamp": "1586416811184",                           # Thursday, April 9, 2020 7:20:11.184 AM GMT
"ApproximateFirstReceiveTimestamp": "1586416821214",        # Thursday, April 9, 2020 7:20:21.214 AM GMT
```

Found near time of SentTimestamp:
```
START RequestId: a99a6e27-8b76-5762-926f-392f45a13e71 Version: $LATEST
[INFO]	2020-04-09T07:20:11.176Z	a99a6e27-8b76-5762-926f-392f45a13e71	Received 2 messages for 2 token(s) with a total value of 14
[INFO]	2020-04-09T07:20:11.176Z	a99a6e27-8b76-5762-926f-392f45a13e71	Document grouping for messages received: {'e0009214-c0a0-4a7b-96e2-d6a83e966ce0': 2}
[INFO]	2020-04-09T07:20:11.176Z	a99a6e27-8b76-5762-926f-392f45a13e71	Attempt 2 of handling 99471 contribution(s) for entity projects/e0009214-c0a0-4a7b-96e2-d6a83e966ce0
[INFO]	2020-04-09T07:20:11.176Z	a99a6e27-8b76-5762-926f-392f45a13e71	Attempt 1 of handling 317 contribution(s) for entity projects/e0009214-c0a0-4a7b-96e2-d6a83e966ce0
[INFO]	2020-04-09T07:20:11.176Z	a99a6e27-8b76-5762-926f-392f45a13e71	Deferring aggregation of 99788 contribution(s) to entity projects/e0009214-c0a0-4a7b-96e2-d6a83e966ce0
[INFO]	2020-04-09T07:20:11.206Z	a99a6e27-8b76-5762-926f-392f45a13e71	Recirculating 2 token(s), after a delay of 0s, for a total value of 13, expiring at 2020-04-09T07:49:15Z
END RequestId: a99a6e27-8b76-5762-926f-392f45a13e71
REPORT RequestId: a99a6e27-8b76-5762-926f-392f45a13e71	Duration: 19857.15 ms	Billed Duration: 19900 ms	Memory Size: 2048 MB	Max Memory Used: 200 MB
```

Found near time of ApproximateFirstReceiveTimestamp:
```
START RequestId: 2236c5fc-8db4-5ec0-aa91-92f44355643c Version: $LATEST
[INFO]	2020-04-09T07:20:21.236Z	2236c5fc-8db4-5ec0-aa91-92f44355643c	Received 1 messages for 2 token(s) with a total value of 12
[INFO]	2020-04-09T07:20:21.236Z	2236c5fc-8db4-5ec0-aa91-92f44355643c	Document grouping for messages received: {'e0009214-c0a0-4a7b-96e2-d6a83e966ce0': 1}
[INFO]	2020-04-09T07:20:21.236Z	2236c5fc-8db4-5ec0-aa91-92f44355643c	Attempt 1 of handling 99788 contribution(s) for entity projects/e0009214-c0a0-4a7b-96e2-d6a83e966ce0
[INFO]	2020-04-09T07:20:21.236Z	2236c5fc-8db4-5ec0-aa91-92f44355643c	Aggregating 99788 contribution(s) to entity projects/e0009214-c0a0-4a7b-96e2-d6a83e966ce0
[INFO]	2020-04-09T07:20:21.289Z	2236c5fc-8db4-5ec0-aa91-92f44355643c	GET https://search-azul-index-dev-atlcgwfjbk6dvrtmiaskbs2swa.us-east-1.es.amazonaws.com:443/_mget?_source_include=entity_id%2Cnum_contributions [status:200 request:0.053s]
[INFO]	2020-04-09T07:20:21.290Z	2236c5fc-8db4-5ec0-aa91-92f44355643c	Reading 144223 expected contribution(s) using scan().
[INFO]	2020-04-09T07:20:21.366Z	2236c5fc-8db4-5ec0-aa91-92f44355643c	GET https://search-azul-index-dev-atlcgwfjbk6dvrtmiaskbs2swa.us-east-1.es.amazonaws.com:443/azul_projects_dev/doc/_search?scroll=5m&size=100 [status:200 request:0.076s]
[INFO]	2020-04-09T07:20:21.489Z	2236c5fc-8db4-5ec0-aa91-92f44355643c	GET https://search-azul-index-dev-atlcgwfjbk6dvrtmiaskbs2swa.us-east-1.es.amazonaws.com:443/_search/scroll?scroll=5m [status:200 request:0.027s]
...
[INFO]	2020-04-09T07:21:59.207Z	2236c5fc-8db4-5ec0-aa91-92f44355643c	GET https://search-azul-index-dev-atlcgwfjbk6dvrtmiaskbs2swa.us-east-1.es.amazonaws.com:443/_search/scroll?scroll=5m [status:200 request:0.040s]
END RequestId: 2236c5fc-8db4-5ec0-aa91-92f44355643c
REPORT RequestId: 2236c5fc-8db4-5ec0-aa91-92f44355643c	Duration: 300021.33 ms	Billed Duration: 300000 ms	Memory Size: 2048 MB	Max Memory Used: 2048 MB
2020-04-09T07:25:01.337Z 2236c5fc-8db4-5ec0-aa91-92f44355643c Task timed out after 300.02 seconds
```

**Comment by hannes-ucsc** [comment] 2020-04-14 02:27
What sticks out to me is `Memory Size: 2048 MB	Max Memory Used: 2048 MB` in the last message. We should run an experiment in `dev` where we increase the memory for the affected lambda by 1G. We should do this without code changes just by tweaking the lambda in the console and then reindex. Could you coordinate that with me for tomorrow?

Keep in mind that every tally is tried 10 times so there must be ten other failures. Do you see log evidence for that?

I have more failed messages from today's reindexing. The difference is that it lists tallies not only for the Tabula muris project, but also for other entities. Could you research this run, too?

[azul-fail-dev.fifo.zip](https://github.com/DataBiosphere/azul/files/4472781/azul-fail-dev.fifo.zip)

**Comment by danielsotirhos** [comment] 2020-04-15 05:37
The memory size of `azul-indexer-dev-write` has been increased from 2048mb to 3008mb and a reindex was run on `dev`. After the reindex completed there were no messages placed in the fail queue however I was able to find a single timed out task related to the processing of the `e0009214` (Tabula Muris) project.

```
START RequestId: c987d169-2b0b-5e90-9069-86795a5688ab Version: $LATEST
[INFO]	2020-04-15T02:19:09.957Z	c987d169-2b0b-5e90-9069-86795a5688ab	Received 10 messages for 2 token(s) with a total value of 8
[INFO]	2020-04-15T02:19:09.958Z	c987d169-2b0b-5e90-9069-86795a5688ab	Document grouping for messages received: {'c548521a-8816-4937-90f1-c85dc70f8ae6': 9, 'e0009214-c0a0-4a7b-96e2-d6a83e966ce0': 1}
[INFO]	2020-04-15T02:19:09.958Z	c987d169-2b0b-5e90-9069-86795a5688ab	Attempt 1 of handling 1 contribution(s) for entity samples/c548521a-8816-4937-90f1-c85dc70f8ae6
[INFO]	2020-04-15T02:19:09.958Z	c987d169-2b0b-5e90-9069-86795a5688ab	Attempt 1 of handling 1 contribution(s) for entity samples/c548521a-8816-4937-90f1-c85dc70f8ae6
[INFO]	2020-04-15T02:19:09.958Z	c987d169-2b0b-5e90-9069-86795a5688ab	Attempt 1 of handling 1 contribution(s) for entity samples/c548521a-8816-4937-90f1-c85dc70f8ae6
[INFO]	2020-04-15T02:19:09.958Z	c987d169-2b0b-5e90-9069-86795a5688ab	Attempt 1 of handling 1 contribution(s) for entity samples/c548521a-8816-4937-90f1-c85dc70f8ae6
[INFO]	2020-04-15T02:19:09.958Z	c987d169-2b0b-5e90-9069-86795a5688ab	Attempt 1 of handling 1 contribution(s) for entity samples/c548521a-8816-4937-90f1-c85dc70f8ae6
[INFO]	2020-04-15T02:19:09.958Z	c987d169-2b0b-5e90-9069-86795a5688ab	Attempt 1 of handling 1 contribution(s) for entity samples/c548521a-8816-4937-90f1-c85dc70f8ae6
[INFO]	2020-04-15T02:19:09.958Z	c987d169-2b0b-5e90-9069-86795a5688ab	Attempt 1 of handling 1 contribution(s) for entity samples/c548521a-8816-4937-90f1-c85dc70f8ae6
[INFO]	2020-04-15T02:19:09.958Z	c987d169-2b0b-5e90-9069-86795a5688ab	Attempt 1 of handling 1 contribution(s) for entity samples/c548521a-8816-4937-90f1-c85dc70f8ae6
[INFO]	2020-04-15T02:19:09.958Z	c987d169-2b0b-5e90-9069-86795a5688ab	Attempt 1 of handling 1 contribution(s) for entity samples/c548521a-8816-4937-90f1-c85dc70f8ae6
[INFO]	2020-04-15T02:19:09.958Z	c987d169-2b0b-5e90-9069-86795a5688ab	Attempt 1 of handling 1 contribution(s) for entity projects/e0009214-c0a0-4a7b-96e2-d6a83e966ce0
[INFO]	2020-04-15T02:19:09.958Z	c987d169-2b0b-5e90-9069-86795a5688ab	Aggregating 1 contribution(s) to entity projects/e0009214-c0a0-4a7b-96e2-d6a83e966ce0
[INFO]	2020-04-15T02:19:10.395Z	c987d169-2b0b-5e90-9069-86795a5688ab	GET https://search-azul-index-dev-atlcgwfjbk6dvrtmiaskbs2swa.us-east-1.es.amazonaws.com:443/_mget?_source_include=entity_id%2Cnum_contributions [status:200 request:0.436s]
[INFO]	2020-04-15T02:19:10.396Z	c987d169-2b0b-5e90-9069-86795a5688ab	Reading 51642 expected contribution(s) using scan().
[INFO]	2020-04-15T02:19:11.615Z	c987d169-2b0b-5e90-9069-86795a5688ab	GET https://search-azul-index-dev-atlcgwfjbk6dvrtmiaskbs2swa.us-east-1.es.amazonaws.com:443/azul_projects_dev/doc/_search?scroll=5m&size=100 [status:200 request:1.219s]
[INFO]	2020-04-15T02:19:12.481Z	c987d169-2b0b-5e90-9069-86795a5688ab	GET https://search-azul-index-dev-atlcgwfjbk6dvrtmiaskbs2swa.us-east-1.es.amazonaws.com:443/_search/scroll?scroll=5m [status:200 request:0.807s]
[INFO]	2020-04-15T02:19:12.999Z	c987d169-2b0b-5e90-9069-86795a5688ab	GET https://search-azul-index-dev-atlcgwfjbk6dvrtmiaskbs2swa.us-east-1.es.amazonaws.com:443/_search/scroll?scroll=5m [status:200 request:0.458s]
...
[INFO]	2020-04-15T02:24:08.788Z	c987d169-2b0b-5e90-9069-86795a5688ab	GET https://search-azul-index-dev-atlcgwfjbk6dvrtmiaskbs2swa.us-east-1.es.amazonaws.com:443/_search/scroll?scroll=5m [status:200 request:0.836s]
[INFO]	2020-04-15T02:24:09.211Z	c987d169-2b0b-5e90-9069-86795a5688ab	GET https://search-azul-index-dev-atlcgwfjbk6dvrtmiaskbs2swa.us-east-1.es.amazonaws.com:443/_search/scroll?scroll=5m [status:200 request:0.360s]
END RequestId: c987d169-2b0b-5e90-9069-86795a5688ab
REPORT RequestId: c987d169-2b0b-5e90-9069-86795a5688ab	Duration: 300062.57 ms	Billed Duration: 300000 ms	Memory Size: 3008 MB	Max Memory Used: 1619 MB
2020-04-15T02:24:09.968Z c987d169-2b0b-5e90-9069-86795a5688ab Task timed out after 300.06 seconds
```

**Comment by danielsotirhos** [comment] 2020-04-27 23:43
A reindex was performed 2020-04-23T17:11:06.669-07:00 with the write lambda `lambda_memory_size` reverted to original value of 2048 MB and resulted in 10 attempts to aggregate contributions from `projects/e0009214-c0a0-4a7b-96e2-d6a83e966ce0` and one message in the fail queue.
[azul-fail-daniel.fifo.txt](https://github.com/DataBiosphere/azul/files/4542548/azul-fail-daniel.fifo.txt)

**Closed** 2020-05-12 22:14 UTC
Labels: code, demoed, orange, task
